// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: core.proto

package server

import (
	"context"

	"core-rpc/internal/logic"
	"core-rpc/internal/svc"
	"core-rpc/pb/core"
)

type CoreServer struct {
	svcCtx *svc.ServiceContext
	core.UnimplementedCoreServer
}

func NewCoreServer(svcCtx *svc.ServiceContext) *CoreServer {
	return &CoreServer{
		svcCtx: svcCtx,
	}
}

// 测试接口
func (s *CoreServer) Test(ctx context.Context, in *core.TestRequest) (*core.TestResponse, error) {
	l := logic.NewTestLogic(ctx, s.svcCtx)
	return l.Test(in)
}

// Login 部分
func (s *CoreServer) Register(ctx context.Context, in *core.RegisterReq) (*core.RegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *CoreServer) EmailLogin(ctx context.Context, in *core.EmailLoginReq) (*core.LoginResp, error) {
	l := logic.NewEmailLoginLogic(ctx, s.svcCtx)
	return l.EmailLogin(in)
}

func (s *CoreServer) ResetPasswordByEmail(ctx context.Context, in *core.ResetPasswordEmailReq) (*core.ResetPasswordEmailResp, error) {
	l := logic.NewResetPasswordByEmailLogic(ctx, s.svcCtx)
	return l.ResetPasswordByEmail(in)
}

func (s *CoreServer) Logout(ctx context.Context, in *core.LogoutReq) (*core.LogoutResp, error) {
	l := logic.NewLogoutLogic(ctx, s.svcCtx)
	return l.Logout(in)
}

// Category 部分
func (s *CoreServer) CreateCategory(ctx context.Context, in *core.CreateCategoryReq) (*core.CreateCategoryResp, error) {
	l := logic.NewCreateCategoryLogic(ctx, s.svcCtx)
	return l.CreateCategory(in)
}

func (s *CoreServer) ListCategories(ctx context.Context, in *core.ListCategoriesReq) (*core.ListCategoriesResp, error) {
	l := logic.NewListCategoriesLogic(ctx, s.svcCtx)
	return l.ListCategories(in)
}

func (s *CoreServer) DeleteCategory(ctx context.Context, in *core.DeleteCategoryReq) (*core.DeleteCategoryResp, error) {
	l := logic.NewDeleteCategoryLogic(ctx, s.svcCtx)
	return l.DeleteCategory(in)
}

// Article 部分
func (s *CoreServer) CreateArticle(ctx context.Context, in *core.CreateArticleReq) (*core.CreateArticleResp, error) {
	l := logic.NewCreateArticleLogic(ctx, s.svcCtx)
	return l.CreateArticle(in)
}

func (s *CoreServer) UpdateArticle(ctx context.Context, in *core.UpdateArticleReq) (*core.UpdateArticleResp, error) {
	l := logic.NewUpdateArticleLogic(ctx, s.svcCtx)
	return l.UpdateArticle(in)
}

func (s *CoreServer) DeleteArticle(ctx context.Context, in *core.DeleteArticleReq) (*core.DeleteArticleResp, error) {
	l := logic.NewDeleteArticleLogic(ctx, s.svcCtx)
	return l.DeleteArticle(in)
}

func (s *CoreServer) GetArticleDetail(ctx context.Context, in *core.GetArticleDetailReq) (*core.GetArticleDetailResp, error) {
	l := logic.NewGetArticleDetailLogic(ctx, s.svcCtx)
	return l.GetArticleDetail(in)
}

func (s *CoreServer) ListArticles(ctx context.Context, in *core.ListArticlesReq) (*core.ListArticlesResp, error) {
	l := logic.NewListArticlesLogic(ctx, s.svcCtx)
	return l.ListArticles(in)
}

func (s *CoreServer) SearchArticles(ctx context.Context, in *core.SearchArticlesReq) (*core.SearchArticlesResp, error) {
	l := logic.NewSearchArticlesLogic(ctx, s.svcCtx)
	return l.SearchArticles(in)
}

// interaction 部分
func (s *CoreServer) LikeArticle(ctx context.Context, in *core.LikeArticleReq) (*core.LikeArticleResp, error) {
	l := logic.NewLikeArticleLogic(ctx, s.svcCtx)
	return l.LikeArticle(in)
}

func (s *CoreServer) FavorArticle(ctx context.Context, in *core.FavoriteArticleReq) (*core.FavoriteArticleResp, error) {
	l := logic.NewFavorArticleLogic(ctx, s.svcCtx)
	return l.FavorArticle(in)
}

func (s *CoreServer) LikeComment(ctx context.Context, in *core.LikeCommentReq) (*core.LikeCommentResp, error) {
	l := logic.NewLikeCommentLogic(ctx, s.svcCtx)
	return l.LikeComment(in)
}

// comment 部分
func (s *CoreServer) CreateComment(ctx context.Context, in *core.CreateCommentReq) (*core.CreateCommentResp, error) {
	l := logic.NewCreateCommentLogic(ctx, s.svcCtx)
	return l.CreateComment(in)
}

func (s *CoreServer) CreateReply(ctx context.Context, in *core.CreateReplyReq) (*core.CreateReplyResp, error) {
	l := logic.NewCreateReplyLogic(ctx, s.svcCtx)
	return l.CreateReply(in)
}

func (s *CoreServer) DeleteComment(ctx context.Context, in *core.DeleteCommentReq) (*core.DeleteCommentResp, error) {
	l := logic.NewDeleteCommentLogic(ctx, s.svcCtx)
	return l.DeleteComment(in)
}

func (s *CoreServer) GetArticleComments(ctx context.Context, in *core.GetArticleCommentsReq) (*core.GetArticleCommentsResp, error) {
	l := logic.NewGetArticleCommentsLogic(ctx, s.svcCtx)
	return l.GetArticleComments(in)
}

func (s *CoreServer) GetCommentReplies(ctx context.Context, in *core.GetCommentRepliesReq) (*core.GetCommentRepliesResp, error) {
	l := logic.NewGetCommentRepliesLogic(ctx, s.svcCtx)
	return l.GetCommentReplies(in)
}

func (s *CoreServer) GetUserComments(ctx context.Context, in *core.GetUserCommentsReq) (*core.GetUserCommentsResp, error) {
	l := logic.NewGetUserCommentsLogic(ctx, s.svcCtx)
	return l.GetUserComments(in)
}
