// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: core.proto

package server

import (
	"context"

	"core-rpc/internal/logic"
	"core-rpc/internal/svc"
	"core-rpc/pb/core"
)

type CoreServer struct {
	svcCtx *svc.ServiceContext
	core.UnimplementedCoreServer
}

func NewCoreServer(svcCtx *svc.ServiceContext) *CoreServer {
	return &CoreServer{
		svcCtx: svcCtx,
	}
}

// 测试接口
func (s *CoreServer) Test(ctx context.Context, in *core.TestRequest) (*core.TestResponse, error) {
	l := logic.NewTestLogic(ctx, s.svcCtx)
	return l.Test(in)
}

// Login 部分
func (s *CoreServer) Register(ctx context.Context, in *core.RegisterReq) (*core.RegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *CoreServer) EmailLogin(ctx context.Context, in *core.EmailLoginReq) (*core.LoginResp, error) {
	l := logic.NewEmailLoginLogic(ctx, s.svcCtx)
	return l.EmailLogin(in)
}

func (s *CoreServer) ResetPasswordByEmail(ctx context.Context, in *core.ResetPasswordEmailReq) (*core.ResetPasswordEmailResp, error) {
	l := logic.NewResetPasswordByEmailLogic(ctx, s.svcCtx)
	return l.ResetPasswordByEmail(in)
}

func (s *CoreServer) Logout(ctx context.Context, in *core.LogoutReq) (*core.LogoutResp, error) {
	l := logic.NewLogoutLogic(ctx, s.svcCtx)
	return l.Logout(in)
}

// Article 部分
func (s *CoreServer) CreateArticle(ctx context.Context, in *core.CreateArticleReq) (*core.CreateArticleResp, error) {
	l := logic.NewCreateArticleLogic(ctx, s.svcCtx)
	return l.CreateArticle(in)
}

func (s *CoreServer) UpdateArticle(ctx context.Context, in *core.UpdateArticleReq) (*core.UpdateArticleResp, error) {
	l := logic.NewUpdateArticleLogic(ctx, s.svcCtx)
	return l.UpdateArticle(in)
}

func (s *CoreServer) DeleteArticle(ctx context.Context, in *core.DeleteArticleReq) (*core.DeleteArticleResp, error) {
	l := logic.NewDeleteArticleLogic(ctx, s.svcCtx)
	return l.DeleteArticle(in)
}

func (s *CoreServer) GetArticleDetail(ctx context.Context, in *core.GetArticleDetailReq) (*core.GetArticleDetailResp, error) {
	l := logic.NewGetArticleDetailLogic(ctx, s.svcCtx)
	return l.GetArticleDetail(in)
}

func (s *CoreServer) ListArticles(ctx context.Context, in *core.ListArticlesReq) (*core.ListArticlesResp, error) {
	l := logic.NewListArticlesLogic(ctx, s.svcCtx)
	return l.ListArticles(in)
}

func (s *CoreServer) SearchArticles(ctx context.Context, in *core.SearchArticlesReq) (*core.SearchArticlesResp, error) {
	l := logic.NewSearchArticlesLogic(ctx, s.svcCtx)
	return l.SearchArticles(in)
}

// interaction 部分
func (s *CoreServer) LikeArticle(ctx context.Context, in *core.LikeArticleReq) (*core.LikeArticleResp, error) {
	l := logic.NewLikeArticleLogic(ctx, s.svcCtx)
	return l.LikeArticle(in)
}

func (s *CoreServer) FavorArticle(ctx context.Context, in *core.FavoriteArticleReq) (*core.FavoriteArticleResp, error) {
	l := logic.NewFavorArticleLogic(ctx, s.svcCtx)
	return l.FavorArticle(in)
}
