// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package article

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	articleFieldNames          = builder.RawFieldNames(&Article{})
	articleRows                = strings.Join(articleFieldNames, ",")
	articleRowsExpectAutoSet   = strings.Join(stringx.Remove(articleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	articleRowsWithPlaceHolder = strings.Join(stringx.Remove(articleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	articleModel interface {
		Insert(ctx context.Context, data *Article) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Article, error)
		Update(ctx context.Context, data *Article) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultArticleModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Article struct {
		Id           uint64         `db:"id"`            // 主键ID
		CreatedAt    time.Time      `db:"created_at"`    // 创建时间
		UpdatedAt    time.Time      `db:"updated_at"`    // 更新时间
		DeletedAt    sql.NullTime   `db:"deleted_at"`    // 软删除时间
		UserId       uint64         `db:"user_id"`       // 作者用户ID
		CategoryId   uint64         `db:"category_id"`   // 分类ID
		Title        string         `db:"title"`         // 文章标题
		Summary      string         `db:"summary"`       // 文章摘要
		Content      sql.NullString `db:"content"`       // 文章内容
		Cover        string         `db:"cover"`         // 封面图URL
		ViewCount    uint64         `db:"view_count"`    // 浏览量
		LikeCount    uint64         `db:"like_count"`    // 点赞数
		FavorCount   uint64         `db:"favor_count"`   // 收藏数
		CommentCount uint64         `db:"comment_count"` // 评论数
	}
)

func newArticleModel(conn sqlx.SqlConn) *defaultArticleModel {
	return &defaultArticleModel{
		conn:  conn,
		table: "`article`",
	}
}

func (m *defaultArticleModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultArticleModel) FindOne(ctx context.Context, id uint64) (*Article, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", articleRows, m.table)
	var resp Article
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultArticleModel) Insert(ctx context.Context, data *Article) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, articleRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.DeletedAt, data.UserId, data.CategoryId, data.Title, data.Summary, data.Content, data.Cover, data.ViewCount, data.LikeCount, data.FavorCount, data.CommentCount)
	return ret, err
}

func (m *defaultArticleModel) Update(ctx context.Context, data *Article) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, articleRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.DeletedAt, data.UserId, data.CategoryId, data.Title, data.Summary, data.Content, data.Cover, data.ViewCount, data.LikeCount, data.FavorCount, data.CommentCount, data.Id)
	return err
}

func (m *defaultArticleModel) tableName() string {
	return m.table
}
