// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: agent.proto

package server

import (
	"context"

	"other-rpc/internal/logic"
	"other-rpc/internal/svc"
	"other-rpc/pb/agent"
)

type AgentServer struct {
	svcCtx *svc.ServiceContext
	agent.UnimplementedAgentServer
}

func NewAgentServer(svcCtx *svc.ServiceContext) *AgentServer {
	return &AgentServer{
		svcCtx: svcCtx,
	}
}

func (s *AgentServer) Test(ctx context.Context, in *agent.TestRequest) (*agent.TestResponse, error) {
	l := logic.NewTestLogic(ctx, s.svcCtx)
	return l.Test(in)
}

// Build 从知识库目录构建向量索引（需先构建才能 Chat）
func (s *AgentServer) Build(ctx context.Context, in *agent.BuildRequest) (*agent.BuildResponse, error) {
	l := logic.NewBuildLogic(ctx, s.svcCtx)
	return l.Build(in)
}

// Chat 基于已构建索引的 RAG 问答
func (s *AgentServer) Chat(ctx context.Context, in *agent.ChatRequest) (*agent.ChatResponse, error) {
	l := logic.NewChatLogic(ctx, s.svcCtx)
	return l.Chat(in)
}
