// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: agent.proto

package server

import (
	"context"

	"other-rpc/internal/logic"
	"other-rpc/internal/svc"
	"other-rpc/pb/agent"
)

type AgentServer struct {
	svcCtx *svc.ServiceContext
	agent.UnimplementedAgentServer
}

func NewAgentServer(svcCtx *svc.ServiceContext) *AgentServer {
	return &AgentServer{
		svcCtx: svcCtx,
	}
}

func (s *AgentServer) Test(ctx context.Context, in *agent.TestRequest) (*agent.TestResponse, error) {
	l := logic.NewTestLogic(ctx, s.svcCtx)
	return l.Test(in)
}
