// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: agent.proto

package server

import (
	"context"

	"other-rpc/internal/logic"
	"other-rpc/internal/svc"
	"other-rpc/pb/agent"
)

type AgentServer struct {
	svcCtx *svc.ServiceContext
	agent.UnimplementedAgentServer
}

func NewAgentServer(svcCtx *svc.ServiceContext) *AgentServer {
	return &AgentServer{
		svcCtx: svcCtx,
	}
}

func (s *AgentServer) Test(ctx context.Context, in *agent.TestRequest) (*agent.TestResponse, error) {
	l := logic.NewTestLogic(ctx, s.svcCtx)
	return l.Test(in)
}

// agent section
func (s *AgentServer) Chat(ctx context.Context, in *agent.ChatRequest) (*agent.ChatResponse, error) {
	l := logic.NewChatLogic(ctx, s.svcCtx)
	return l.Chat(in)
}

func (s *AgentServer) ChatStream(in *agent.ChatRequest, stream agent.Agent_ChatStreamServer) error {
	l := logic.NewChatStreamLogic(stream.Context(), s.svcCtx)
	return l.ChatStream(in, stream)
}

func (s *AgentServer) SwitchRetriever(ctx context.Context, in *agent.SwitchRetrieverRequest) (*agent.SwitchRetrieverResponse, error) {
	l := logic.NewSwitchRetrieverLogic(ctx, s.svcCtx)
	return l.SwitchRetriever(in)
}

// vector section
func (s *AgentServer) Build(ctx context.Context, in *agent.BuildRequest) (*agent.BuildResponse, error) {
	l := logic.NewBuildLogic(ctx, s.svcCtx)
	return l.Build(in)
}

func (s *AgentServer) ListCollections(ctx context.Context, in *agent.ListCollectionsRequest) (*agent.ListCollectionsResponse, error) {
	l := logic.NewListCollectionsLogic(ctx, s.svcCtx)
	return l.ListCollections(in)
}

func (s *AgentServer) DeleteCollection(ctx context.Context, in *agent.DeleteCollectionRequest) (*agent.DeleteCollectionResponse, error) {
	l := logic.NewDeleteCollectionLogic(ctx, s.svcCtx)
	return l.DeleteCollection(in)
}
