// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: core.proto

package core

import (
	"context"

	"core-rpc/pb/core"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	EmailCaptchaReq        = core.EmailCaptchaReq
	EmailCaptchaResp       = core.EmailCaptchaResp
	EmailLoginReq          = core.EmailLoginReq
	LoginReq               = core.LoginReq
	LoginResp              = core.LoginResp
	LogoutReq              = core.LogoutReq
	LogoutResp             = core.LogoutResp
	RegisterReq            = core.RegisterReq
	RegisterResp           = core.RegisterResp
	ResetPasswordEmailReq  = core.ResetPasswordEmailReq
	ResetPasswordEmailResp = core.ResetPasswordEmailResp
	TestRequest            = core.TestRequest
	TestResponse           = core.TestResponse

	Core interface {
		// 测试接口
		Test(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error)
		// Login 服务
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		EmailLogin(ctx context.Context, in *EmailLoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		ResetPasswordByEmail(ctx context.Context, in *ResetPasswordEmailReq, opts ...grpc.CallOption) (*ResetPasswordEmailResp, error)
		Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*LogoutResp, error)
		EmailCaptcha(ctx context.Context, in *EmailCaptchaReq, opts ...grpc.CallOption) (*EmailCaptchaResp, error)
	}

	defaultCore struct {
		cli zrpc.Client
	}
)

func NewCore(cli zrpc.Client) Core {
	return &defaultCore{
		cli: cli,
	}
}

// 测试接口
func (m *defaultCore) Test(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.Test(ctx, in, opts...)
}

// Login 服务
func (m *defaultCore) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultCore) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultCore) EmailLogin(ctx context.Context, in *EmailLoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.EmailLogin(ctx, in, opts...)
}

func (m *defaultCore) ResetPasswordByEmail(ctx context.Context, in *ResetPasswordEmailReq, opts ...grpc.CallOption) (*ResetPasswordEmailResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.ResetPasswordByEmail(ctx, in, opts...)
}

func (m *defaultCore) Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*LogoutResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.Logout(ctx, in, opts...)
}

func (m *defaultCore) EmailCaptcha(ctx context.Context, in *EmailCaptchaReq, opts ...grpc.CallOption) (*EmailCaptchaResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.EmailCaptcha(ctx, in, opts...)
}
