// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: agent.proto

package agent_client

import (
	"context"

	"other-rpc/pb/agent"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BuildRequest             = agent.BuildRequest
	BuildResponse            = agent.BuildResponse
	ChatRequest              = agent.ChatRequest
	ChatResponse             = agent.ChatResponse
	ChatStreamChunk          = agent.ChatStreamChunk
	CollectionInfo           = agent.CollectionInfo
	DeleteCollectionRequest  = agent.DeleteCollectionRequest
	DeleteCollectionResponse = agent.DeleteCollectionResponse
	ListCollectionsRequest   = agent.ListCollectionsRequest
	ListCollectionsResponse  = agent.ListCollectionsResponse
	SwitchRetrieverRequest   = agent.SwitchRetrieverRequest
	SwitchRetrieverResponse  = agent.SwitchRetrieverResponse
	TestRequest              = agent.TestRequest
	TestResponse             = agent.TestResponse

	Agent interface {
		Test(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error)
		// agent section
		Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error)
		ChatStream(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (agent.Agent_ChatStreamClient, error)
		SwitchRetriever(ctx context.Context, in *SwitchRetrieverRequest, opts ...grpc.CallOption) (*SwitchRetrieverResponse, error)
		// vector section
		Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (*BuildResponse, error)
		ListCollections(ctx context.Context, in *ListCollectionsRequest, opts ...grpc.CallOption) (*ListCollectionsResponse, error)
		DeleteCollection(ctx context.Context, in *DeleteCollectionRequest, opts ...grpc.CallOption) (*DeleteCollectionResponse, error)
	}

	defaultAgent struct {
		cli zrpc.Client
	}
)

func NewAgent(cli zrpc.Client) Agent {
	return &defaultAgent{
		cli: cli,
	}
}

func (m *defaultAgent) Test(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error) {
	client := agent.NewAgentClient(m.cli.Conn())
	return client.Test(ctx, in, opts...)
}

// agent section
func (m *defaultAgent) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error) {
	client := agent.NewAgentClient(m.cli.Conn())
	return client.Chat(ctx, in, opts...)
}

func (m *defaultAgent) ChatStream(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (agent.Agent_ChatStreamClient, error) {
	client := agent.NewAgentClient(m.cli.Conn())
	return client.ChatStream(ctx, in, opts...)
}

func (m *defaultAgent) SwitchRetriever(ctx context.Context, in *SwitchRetrieverRequest, opts ...grpc.CallOption) (*SwitchRetrieverResponse, error) {
	client := agent.NewAgentClient(m.cli.Conn())
	return client.SwitchRetriever(ctx, in, opts...)
}

// vector section
func (m *defaultAgent) Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (*BuildResponse, error) {
	client := agent.NewAgentClient(m.cli.Conn())
	return client.Build(ctx, in, opts...)
}

func (m *defaultAgent) ListCollections(ctx context.Context, in *ListCollectionsRequest, opts ...grpc.CallOption) (*ListCollectionsResponse, error) {
	client := agent.NewAgentClient(m.cli.Conn())
	return client.ListCollections(ctx, in, opts...)
}

func (m *defaultAgent) DeleteCollection(ctx context.Context, in *DeleteCollectionRequest, opts ...grpc.CallOption) (*DeleteCollectionResponse, error) {
	client := agent.NewAgentClient(m.cli.Conn())
	return client.DeleteCollection(ctx, in, opts...)
}
