// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: agent.proto

package agent_client

import (
	"context"

	"other-rpc/pb/agent"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BuildRequest  = agent.BuildRequest
	BuildResponse = agent.BuildResponse
	ChatRequest   = agent.ChatRequest
	ChatResponse  = agent.ChatResponse
	TestRequest   = agent.TestRequest
	TestResponse  = agent.TestResponse

	Agent interface {
		Test(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error)
		// Build 从知识库目录构建向量索引（需先构建才能 Chat）
		Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (*BuildResponse, error)
		// Chat 基于已构建索引的 RAG 问答
		Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error)
	}

	defaultAgent struct {
		cli zrpc.Client
	}
)

func NewAgent(cli zrpc.Client) Agent {
	return &defaultAgent{
		cli: cli,
	}
}

func (m *defaultAgent) Test(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error) {
	client := agent.NewAgentClient(m.cli.Conn())
	return client.Test(ctx, in, opts...)
}

// Build 从知识库目录构建向量索引（需先构建才能 Chat）
func (m *defaultAgent) Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (*BuildResponse, error) {
	client := agent.NewAgentClient(m.cli.Conn())
	return client.Build(ctx, in, opts...)
}

// Chat 基于已构建索引的 RAG 问答
func (m *defaultAgent) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error) {
	client := agent.NewAgentClient(m.cli.Conn())
	return client.Chat(ctx, in, opts...)
}
