syntax = "proto3"; //指定版本

package core;
// 包名
option go_package = "./category";

// 定义服务名
service Core {
  rpc CreateCategory(CreateCategoryReq) returns (CreateCategoryResp){};  //  创建分类
  rpc ListCategories(ListCategoriesReq) returns (ListCategoriesResp){};  //  分类列表
  rpc DeleteCategory(DeleteCategoryReq) returns (DeleteCategoryResp){};  //  删除分类
}

// =====================================================================================================================

message CreateCategoryReq {
  string name = 1;
}
message CreateCategoryResp {}

message CategoryInfo {
  uint64 id = 1;
  string name = 2;
}

message ListCategoriesReq {}
message ListCategoriesResp {
  repeated CategoryInfo categories = 1;
}

message DeleteCategoryReq {
  uint64 id = 1;
}
message DeleteCategoryResp {}