// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: core.proto

package core_client

import (
	"context"

	"core-rpc/pb/core"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ArticleInfo            = core.ArticleInfo
	CategoryInfo           = core.CategoryInfo
	CreateArticleReq       = core.CreateArticleReq
	CreateArticleResp      = core.CreateArticleResp
	CreateCategoryReq      = core.CreateCategoryReq
	CreateCategoryResp     = core.CreateCategoryResp
	DeleteArticleReq       = core.DeleteArticleReq
	DeleteArticleResp      = core.DeleteArticleResp
	DeleteCategoryReq      = core.DeleteCategoryReq
	DeleteCategoryResp     = core.DeleteCategoryResp
	EmailLoginReq          = core.EmailLoginReq
	FavoriteArticleReq     = core.FavoriteArticleReq
	FavoriteArticleResp    = core.FavoriteArticleResp
	GetArticleDetailReq    = core.GetArticleDetailReq
	GetArticleDetailResp   = core.GetArticleDetailResp
	LikeArticleReq         = core.LikeArticleReq
	LikeArticleResp        = core.LikeArticleResp
	ListArticlesReq        = core.ListArticlesReq
	ListArticlesResp       = core.ListArticlesResp
	ListCategoriesReq      = core.ListCategoriesReq
	ListCategoriesResp     = core.ListCategoriesResp
	LoginResp              = core.LoginResp
	LogoutReq              = core.LogoutReq
	LogoutResp             = core.LogoutResp
	RegisterReq            = core.RegisterReq
	RegisterResp           = core.RegisterResp
	ResetPasswordEmailReq  = core.ResetPasswordEmailReq
	ResetPasswordEmailResp = core.ResetPasswordEmailResp
	SearchArticlesReq      = core.SearchArticlesReq
	SearchArticlesResp     = core.SearchArticlesResp
	TestRequest            = core.TestRequest
	TestResponse           = core.TestResponse
	UpdateArticleReq       = core.UpdateArticleReq
	UpdateArticleResp      = core.UpdateArticleResp

	Core interface {
		// 测试接口
		Test(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error)
		// Login 部分
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
		EmailLogin(ctx context.Context, in *EmailLoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		ResetPasswordByEmail(ctx context.Context, in *ResetPasswordEmailReq, opts ...grpc.CallOption) (*ResetPasswordEmailResp, error)
		Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*LogoutResp, error)
		// Category 部分
		CreateCategory(ctx context.Context, in *CreateCategoryReq, opts ...grpc.CallOption) (*CreateCategoryResp, error)
		ListCategories(ctx context.Context, in *ListCategoriesReq, opts ...grpc.CallOption) (*ListCategoriesResp, error)
		DeleteCategory(ctx context.Context, in *DeleteCategoryReq, opts ...grpc.CallOption) (*DeleteCategoryResp, error)
		// Article 部分
		CreateArticle(ctx context.Context, in *CreateArticleReq, opts ...grpc.CallOption) (*CreateArticleResp, error)
		UpdateArticle(ctx context.Context, in *UpdateArticleReq, opts ...grpc.CallOption) (*UpdateArticleResp, error)
		DeleteArticle(ctx context.Context, in *DeleteArticleReq, opts ...grpc.CallOption) (*DeleteArticleResp, error)
		GetArticleDetail(ctx context.Context, in *GetArticleDetailReq, opts ...grpc.CallOption) (*GetArticleDetailResp, error)
		ListArticles(ctx context.Context, in *ListArticlesReq, opts ...grpc.CallOption) (*ListArticlesResp, error)
		SearchArticles(ctx context.Context, in *SearchArticlesReq, opts ...grpc.CallOption) (*SearchArticlesResp, error)
		// interaction 部分
		LikeArticle(ctx context.Context, in *LikeArticleReq, opts ...grpc.CallOption) (*LikeArticleResp, error)
		FavorArticle(ctx context.Context, in *FavoriteArticleReq, opts ...grpc.CallOption) (*FavoriteArticleResp, error)
	}

	defaultCore struct {
		cli zrpc.Client
	}
)

func NewCore(cli zrpc.Client) Core {
	return &defaultCore{
		cli: cli,
	}
}

// 测试接口
func (m *defaultCore) Test(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.Test(ctx, in, opts...)
}

// Login 部分
func (m *defaultCore) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultCore) EmailLogin(ctx context.Context, in *EmailLoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.EmailLogin(ctx, in, opts...)
}

func (m *defaultCore) ResetPasswordByEmail(ctx context.Context, in *ResetPasswordEmailReq, opts ...grpc.CallOption) (*ResetPasswordEmailResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.ResetPasswordByEmail(ctx, in, opts...)
}

func (m *defaultCore) Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*LogoutResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.Logout(ctx, in, opts...)
}

// Category 部分
func (m *defaultCore) CreateCategory(ctx context.Context, in *CreateCategoryReq, opts ...grpc.CallOption) (*CreateCategoryResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.CreateCategory(ctx, in, opts...)
}

func (m *defaultCore) ListCategories(ctx context.Context, in *ListCategoriesReq, opts ...grpc.CallOption) (*ListCategoriesResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.ListCategories(ctx, in, opts...)
}

func (m *defaultCore) DeleteCategory(ctx context.Context, in *DeleteCategoryReq, opts ...grpc.CallOption) (*DeleteCategoryResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.DeleteCategory(ctx, in, opts...)
}

// Article 部分
func (m *defaultCore) CreateArticle(ctx context.Context, in *CreateArticleReq, opts ...grpc.CallOption) (*CreateArticleResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.CreateArticle(ctx, in, opts...)
}

func (m *defaultCore) UpdateArticle(ctx context.Context, in *UpdateArticleReq, opts ...grpc.CallOption) (*UpdateArticleResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.UpdateArticle(ctx, in, opts...)
}

func (m *defaultCore) DeleteArticle(ctx context.Context, in *DeleteArticleReq, opts ...grpc.CallOption) (*DeleteArticleResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.DeleteArticle(ctx, in, opts...)
}

func (m *defaultCore) GetArticleDetail(ctx context.Context, in *GetArticleDetailReq, opts ...grpc.CallOption) (*GetArticleDetailResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.GetArticleDetail(ctx, in, opts...)
}

func (m *defaultCore) ListArticles(ctx context.Context, in *ListArticlesReq, opts ...grpc.CallOption) (*ListArticlesResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.ListArticles(ctx, in, opts...)
}

func (m *defaultCore) SearchArticles(ctx context.Context, in *SearchArticlesReq, opts ...grpc.CallOption) (*SearchArticlesResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.SearchArticles(ctx, in, opts...)
}

// interaction 部分
func (m *defaultCore) LikeArticle(ctx context.Context, in *LikeArticleReq, opts ...grpc.CallOption) (*LikeArticleResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.LikeArticle(ctx, in, opts...)
}

func (m *defaultCore) FavorArticle(ctx context.Context, in *FavoriteArticleReq, opts ...grpc.CallOption) (*FavoriteArticleResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.FavorArticle(ctx, in, opts...)
}
