// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: core.proto

package core_client

import (
	"context"

	"core-rpc/pb/core"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ArticleInfo                   = core.ArticleInfo
	BatchGetCommentLikeStatusReq  = core.BatchGetCommentLikeStatusReq
	BatchGetCommentLikeStatusResp = core.BatchGetCommentLikeStatusResp
	CategoryInfo                  = core.CategoryInfo
	CommentInfo                   = core.CommentInfo
	CommentLikeStatusItem         = core.CommentLikeStatusItem
	CreateArticleReq              = core.CreateArticleReq
	CreateArticleResp             = core.CreateArticleResp
	CreateCategoryReq             = core.CreateCategoryReq
	CreateCategoryResp            = core.CreateCategoryResp
	CreateCommentReq              = core.CreateCommentReq
	CreateCommentResp             = core.CreateCommentResp
	CreateReplyReq                = core.CreateReplyReq
	CreateReplyResp               = core.CreateReplyResp
	DeleteArticleReq              = core.DeleteArticleReq
	DeleteArticleResp             = core.DeleteArticleResp
	DeleteCategoryReq             = core.DeleteCategoryReq
	DeleteCategoryResp            = core.DeleteCategoryResp
	DeleteCommentReq              = core.DeleteCommentReq
	DeleteCommentResp             = core.DeleteCommentResp
	EmailLoginReq                 = core.EmailLoginReq
	GetArticleCommentsReq         = core.GetArticleCommentsReq
	GetArticleCommentsResp        = core.GetArticleCommentsResp
	GetArticleDetailReq           = core.GetArticleDetailReq
	GetArticleDetailResp          = core.GetArticleDetailResp
	GetArticleLikeStatusReq       = core.GetArticleLikeStatusReq
	GetArticleLikeStatusResp      = core.GetArticleLikeStatusResp
	GetArticlesByCategoryReq      = core.GetArticlesByCategoryReq
	GetCommentRepliesReq          = core.GetCommentRepliesReq
	GetCommentRepliesResp         = core.GetCommentRepliesResp
	GetUserCommentsReq            = core.GetUserCommentsReq
	GetUserCommentsResp           = core.GetUserCommentsResp
	GetUserProfileReq             = core.GetUserProfileReq
	GetUserProfileResp            = core.GetUserProfileResp
	LikeArticleReq                = core.LikeArticleReq
	LikeArticleResp               = core.LikeArticleResp
	LikeCommentReq                = core.LikeCommentReq
	LikeCommentResp               = core.LikeCommentResp
	ListArticlesReq               = core.ListArticlesReq
	ListArticlesResp              = core.ListArticlesResp
	ListCategoriesReq             = core.ListCategoriesReq
	ListCategoriesResp            = core.ListCategoriesResp
	ListUserArticlesReq           = core.ListUserArticlesReq
	ListUserLikedArticlesReq      = core.ListUserLikedArticlesReq
	LoginResp                     = core.LoginResp
	LogoutReq                     = core.LogoutReq
	LogoutResp                    = core.LogoutResp
	RegisterReq                   = core.RegisterReq
	RegisterResp                  = core.RegisterResp
	ResetPasswordEmailReq         = core.ResetPasswordEmailReq
	ResetPasswordEmailResp        = core.ResetPasswordEmailResp
	SearchArticlesReq             = core.SearchArticlesReq
	SearchArticlesResp            = core.SearchArticlesResp
	TestRequest                   = core.TestRequest
	TestResponse                  = core.TestResponse
	UnlikeArticleReq              = core.UnlikeArticleReq
	UnlikeArticleResp             = core.UnlikeArticleResp
	UnlikeCommentReq              = core.UnlikeCommentReq
	UnlikeCommentResp             = core.UnlikeCommentResp
	UpdateArticleReq              = core.UpdateArticleReq
	UpdateArticleResp             = core.UpdateArticleResp
	UpdateUserProfileReq          = core.UpdateUserProfileReq
	UpdateUserProfileResp         = core.UpdateUserProfileResp
	UserProfile                   = core.UserProfile
	ViewArticleReq                = core.ViewArticleReq
	ViewArticleResp               = core.ViewArticleResp

	Core interface {
		// 测试接口
		Test(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error)
		// Login 部分
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
		EmailLogin(ctx context.Context, in *EmailLoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		ResetPasswordByEmail(ctx context.Context, in *ResetPasswordEmailReq, opts ...grpc.CallOption) (*ResetPasswordEmailResp, error)
		Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*LogoutResp, error)
		// person 部分
		GetUserProfile(ctx context.Context, in *GetUserProfileReq, opts ...grpc.CallOption) (*GetUserProfileResp, error)
		UpdateUserProfile(ctx context.Context, in *UpdateUserProfileReq, opts ...grpc.CallOption) (*UpdateUserProfileResp, error)
		ListUserLikedArticles(ctx context.Context, in *ListUserLikedArticlesReq, opts ...grpc.CallOption) (*ListArticlesResp, error)
		ListUserArticles(ctx context.Context, in *ListUserArticlesReq, opts ...grpc.CallOption) (*ListArticlesResp, error)
		// Category 部分
		CreateCategory(ctx context.Context, in *CreateCategoryReq, opts ...grpc.CallOption) (*CreateCategoryResp, error)
		ListCategories(ctx context.Context, in *ListCategoriesReq, opts ...grpc.CallOption) (*ListCategoriesResp, error)
		DeleteCategory(ctx context.Context, in *DeleteCategoryReq, opts ...grpc.CallOption) (*DeleteCategoryResp, error)
		// Article 部分
		CreateArticle(ctx context.Context, in *CreateArticleReq, opts ...grpc.CallOption) (*CreateArticleResp, error)
		UpdateArticle(ctx context.Context, in *UpdateArticleReq, opts ...grpc.CallOption) (*UpdateArticleResp, error)
		DeleteArticle(ctx context.Context, in *DeleteArticleReq, opts ...grpc.CallOption) (*DeleteArticleResp, error)
		GetArticleDetail(ctx context.Context, in *GetArticleDetailReq, opts ...grpc.CallOption) (*GetArticleDetailResp, error)
		ListArticles(ctx context.Context, in *ListArticlesReq, opts ...grpc.CallOption) (*ListArticlesResp, error)
		GetArticlesByCategory(ctx context.Context, in *GetArticlesByCategoryReq, opts ...grpc.CallOption) (*ListArticlesResp, error)
		SearchArticles(ctx context.Context, in *SearchArticlesReq, opts ...grpc.CallOption) (*SearchArticlesResp, error)
		// interaction 部分
		LikeArticle(ctx context.Context, in *LikeArticleReq, opts ...grpc.CallOption) (*LikeArticleResp, error)
		UnlikeArticle(ctx context.Context, in *UnlikeArticleReq, opts ...grpc.CallOption) (*UnlikeArticleResp, error)
		LikeComment(ctx context.Context, in *LikeCommentReq, opts ...grpc.CallOption) (*LikeCommentResp, error)
		UnlikeComment(ctx context.Context, in *UnlikeCommentReq, opts ...grpc.CallOption) (*UnlikeCommentResp, error)
		ViewArticle(ctx context.Context, in *ViewArticleReq, opts ...grpc.CallOption) (*ViewArticleResp, error)
		GetArticleLikeStatus(ctx context.Context, in *GetArticleLikeStatusReq, opts ...grpc.CallOption) (*GetArticleLikeStatusResp, error)
		BatchGetCommentLikeStatus(ctx context.Context, in *BatchGetCommentLikeStatusReq, opts ...grpc.CallOption) (*BatchGetCommentLikeStatusResp, error)
		// comment 部分
		CreateComment(ctx context.Context, in *CreateCommentReq, opts ...grpc.CallOption) (*CreateCommentResp, error)
		CreateReply(ctx context.Context, in *CreateReplyReq, opts ...grpc.CallOption) (*CreateReplyResp, error)
		DeleteComment(ctx context.Context, in *DeleteCommentReq, opts ...grpc.CallOption) (*DeleteCommentResp, error)
		GetArticleComments(ctx context.Context, in *GetArticleCommentsReq, opts ...grpc.CallOption) (*GetArticleCommentsResp, error)
		GetCommentReplies(ctx context.Context, in *GetCommentRepliesReq, opts ...grpc.CallOption) (*GetCommentRepliesResp, error)
		GetUserComments(ctx context.Context, in *GetUserCommentsReq, opts ...grpc.CallOption) (*GetUserCommentsResp, error)
	}

	defaultCore struct {
		cli zrpc.Client
	}
)

func NewCore(cli zrpc.Client) Core {
	return &defaultCore{
		cli: cli,
	}
}

// 测试接口
func (m *defaultCore) Test(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.Test(ctx, in, opts...)
}

// Login 部分
func (m *defaultCore) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultCore) EmailLogin(ctx context.Context, in *EmailLoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.EmailLogin(ctx, in, opts...)
}

func (m *defaultCore) ResetPasswordByEmail(ctx context.Context, in *ResetPasswordEmailReq, opts ...grpc.CallOption) (*ResetPasswordEmailResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.ResetPasswordByEmail(ctx, in, opts...)
}

func (m *defaultCore) Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*LogoutResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.Logout(ctx, in, opts...)
}

// person 部分
func (m *defaultCore) GetUserProfile(ctx context.Context, in *GetUserProfileReq, opts ...grpc.CallOption) (*GetUserProfileResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.GetUserProfile(ctx, in, opts...)
}

func (m *defaultCore) UpdateUserProfile(ctx context.Context, in *UpdateUserProfileReq, opts ...grpc.CallOption) (*UpdateUserProfileResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.UpdateUserProfile(ctx, in, opts...)
}

func (m *defaultCore) ListUserLikedArticles(ctx context.Context, in *ListUserLikedArticlesReq, opts ...grpc.CallOption) (*ListArticlesResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.ListUserLikedArticles(ctx, in, opts...)
}

func (m *defaultCore) ListUserArticles(ctx context.Context, in *ListUserArticlesReq, opts ...grpc.CallOption) (*ListArticlesResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.ListUserArticles(ctx, in, opts...)
}

// Category 部分
func (m *defaultCore) CreateCategory(ctx context.Context, in *CreateCategoryReq, opts ...grpc.CallOption) (*CreateCategoryResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.CreateCategory(ctx, in, opts...)
}

func (m *defaultCore) ListCategories(ctx context.Context, in *ListCategoriesReq, opts ...grpc.CallOption) (*ListCategoriesResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.ListCategories(ctx, in, opts...)
}

func (m *defaultCore) DeleteCategory(ctx context.Context, in *DeleteCategoryReq, opts ...grpc.CallOption) (*DeleteCategoryResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.DeleteCategory(ctx, in, opts...)
}

// Article 部分
func (m *defaultCore) CreateArticle(ctx context.Context, in *CreateArticleReq, opts ...grpc.CallOption) (*CreateArticleResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.CreateArticle(ctx, in, opts...)
}

func (m *defaultCore) UpdateArticle(ctx context.Context, in *UpdateArticleReq, opts ...grpc.CallOption) (*UpdateArticleResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.UpdateArticle(ctx, in, opts...)
}

func (m *defaultCore) DeleteArticle(ctx context.Context, in *DeleteArticleReq, opts ...grpc.CallOption) (*DeleteArticleResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.DeleteArticle(ctx, in, opts...)
}

func (m *defaultCore) GetArticleDetail(ctx context.Context, in *GetArticleDetailReq, opts ...grpc.CallOption) (*GetArticleDetailResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.GetArticleDetail(ctx, in, opts...)
}

func (m *defaultCore) ListArticles(ctx context.Context, in *ListArticlesReq, opts ...grpc.CallOption) (*ListArticlesResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.ListArticles(ctx, in, opts...)
}

func (m *defaultCore) GetArticlesByCategory(ctx context.Context, in *GetArticlesByCategoryReq, opts ...grpc.CallOption) (*ListArticlesResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.GetArticlesByCategory(ctx, in, opts...)
}

func (m *defaultCore) SearchArticles(ctx context.Context, in *SearchArticlesReq, opts ...grpc.CallOption) (*SearchArticlesResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.SearchArticles(ctx, in, opts...)
}

// interaction 部分
func (m *defaultCore) LikeArticle(ctx context.Context, in *LikeArticleReq, opts ...grpc.CallOption) (*LikeArticleResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.LikeArticle(ctx, in, opts...)
}

func (m *defaultCore) UnlikeArticle(ctx context.Context, in *UnlikeArticleReq, opts ...grpc.CallOption) (*UnlikeArticleResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.UnlikeArticle(ctx, in, opts...)
}

func (m *defaultCore) LikeComment(ctx context.Context, in *LikeCommentReq, opts ...grpc.CallOption) (*LikeCommentResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.LikeComment(ctx, in, opts...)
}

func (m *defaultCore) UnlikeComment(ctx context.Context, in *UnlikeCommentReq, opts ...grpc.CallOption) (*UnlikeCommentResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.UnlikeComment(ctx, in, opts...)
}

func (m *defaultCore) ViewArticle(ctx context.Context, in *ViewArticleReq, opts ...grpc.CallOption) (*ViewArticleResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.ViewArticle(ctx, in, opts...)
}

func (m *defaultCore) GetArticleLikeStatus(ctx context.Context, in *GetArticleLikeStatusReq, opts ...grpc.CallOption) (*GetArticleLikeStatusResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.GetArticleLikeStatus(ctx, in, opts...)
}

func (m *defaultCore) BatchGetCommentLikeStatus(ctx context.Context, in *BatchGetCommentLikeStatusReq, opts ...grpc.CallOption) (*BatchGetCommentLikeStatusResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.BatchGetCommentLikeStatus(ctx, in, opts...)
}

// comment 部分
func (m *defaultCore) CreateComment(ctx context.Context, in *CreateCommentReq, opts ...grpc.CallOption) (*CreateCommentResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.CreateComment(ctx, in, opts...)
}

func (m *defaultCore) CreateReply(ctx context.Context, in *CreateReplyReq, opts ...grpc.CallOption) (*CreateReplyResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.CreateReply(ctx, in, opts...)
}

func (m *defaultCore) DeleteComment(ctx context.Context, in *DeleteCommentReq, opts ...grpc.CallOption) (*DeleteCommentResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.DeleteComment(ctx, in, opts...)
}

func (m *defaultCore) GetArticleComments(ctx context.Context, in *GetArticleCommentsReq, opts ...grpc.CallOption) (*GetArticleCommentsResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.GetArticleComments(ctx, in, opts...)
}

func (m *defaultCore) GetCommentReplies(ctx context.Context, in *GetCommentRepliesReq, opts ...grpc.CallOption) (*GetCommentRepliesResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.GetCommentReplies(ctx, in, opts...)
}

func (m *defaultCore) GetUserComments(ctx context.Context, in *GetUserCommentsReq, opts ...grpc.CallOption) (*GetUserCommentsResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.GetUserComments(ctx, in, opts...)
}
