syntax = "proto3"; // 指定版本

package article; // 包名：类似命名空间

// 生成代码的路径配置
option go_package = "./article";

// 定义服务名
service Article {
  rpc GetCategoryList(GetCategoryListReq) returns(GetCategoryListResp){};  //   获取分类列表（返回数组）
  rpc GetArticlesByCategory(GetArticlesByCategoryReq) returns(GetArticlesByCategoryResp){};  //   获取分类下的所有文章

  rpc GetArticleById(GetArticleByIdReq) returns(GetArticleByIdResp){};  //  根据文章id获取对应博客的内容
  rpc GetArticleList(GetArticleListReq) returns(GetArticleListResp){};  //  获取文章列表（返回数组）
  rpc GetArtByUserID(GetArtByUserIDReq) returns (GetArtByUserIDResp){}; // 根据用户id获取对应博客的内容

  rpc SearchArticle(SearchArticleReq) returns(SearchArticleResp){};  //  搜索文章
  rpc CreateArticle(CreateArticleReq) returns(CreateArticleResp){};  //  创建文章
  rpc DeleteArticle(DeleteArticleReq) returns(DeleteArticleResp){};  //  删除文章

}


//======================================================================================================================
// 分类部分
message GetCategoryListReq {
}
message Category {
  uint64  id   = 1; // 分类ID
  string name = 2; // 分类名称
  uint64  parentId = 3; // 父id
  bool   status = 4; // 状态（true=启用，false=禁用）
}
message GetCategoryListResp {
  repeated Category categories = 1; // 分类数组（使用repeated定义）
}

message GetArticlesByCategoryReq {
  uint64 categoryId = 1; // 分类ID
  int32 page = 2;        // 页码，默认1
  int32 size = 3;        // 每页条数，默认10
}
message GetArticlesByCategoryResp {
  repeated Art articles = 1; // 文章数组
  int32 page = 2;                    // 当前页
  int32 size = 3;                    // 每页条数
  int32 total = 4;                   // 总条数
}
message Art {
  uint64 id = 1; // 文章ID
  string title = 2; // 文章标题
  string CategoryName = 3;  // 分类名称
  string FeaturedImage = 4; // 文章封面
  uint64 ReadCount = 5; // 阅读数
  uint64 CommentCount = 6; // 评论数
  string description = 7; // 文章描述
  string createdAt = 8; // 创建时间
  string Author = 9; // 作者
  uint64 LikeCount = 10; // 点赞数
}
//======================================================================================================================
// 文章内容部分
message GetArticleListReq {
  int32 page = 1;        // 页码，默认1
  int32 size = 2;        // 每页条数，默认10
}
message GetArticleListResp {
  repeated Art articles = 1; // 文章数组
  int32 page = 2;                    // 当前页
  int32 size = 3;                    // 每页条数
  int32 total = 4;                   // 总条数
}

message GetArticleByIdReq {
  uint64 id = 1; // 文章ID
}
message GetArticleByIdResp {
  uint64 id = 1; // 文章ID
  string title = 2; // 文章标题
  string content = 3; // 文章内容
  string categoryName = 4; // 分类ID
  string FeaturedImg =5;
  string createdAt = 6; // 创建时间
  uint64 ReadCount = 7; // 阅读数
  uint64 LikeCount = 8; // 点赞数
  uint64 CommentCount = 9; // 评论数
  bool status = 10; // 状态（true=启用，false=禁用）
  bool isTop = 11; // 是否置顶
  string Author = 12; // 作者
  string Description =13;
}

message GetArtByUserIDReq{
  uint64 id =1;
}
message GetArtByUserIDResp{
  repeated Art articles = 1; // 文章数组
}
//======================================================================================================
// 文章操作部分
message SearchArticleReq {
  string keyword = 1; // 搜索关键词
  int32 page = 2;        // 页码，默认1
  int32 size = 3;        // 每页条数，默认10
}
message SearchArticleResp {
  repeated Art articles = 1; // 文章数组
  int32 page = 2;                    // 当前页
  int32 size = 3;                    // 每页条数
  int32 total = 4;                   // 总条数
}

message CreateArticleReq {
  string title = 1; // 文章标题
  string content = 2; // 文章内容
  uint64 categoryId = 3; // 分类ID
  string FeaturedImage = 4; // 文章封面
  string description =5;//摘要
  uint64 userId = 6; // 用户ID（作者）
}
message CreateArticleResp {
}

message DeleteArticleReq{
  uint64 id=1;
}
message DeleteArticleResp{}
//======================================================================================================================
// 缓存部分 浏览量和点赞
message CacheReadReq{
  string id = 1;
}
message CacheReadResp{}

message CacheLikeReq{
  uint64 UserId = 1;
  uint64 ArtId = 2;
}
message CacheLikeResp{
  bool Liked = 1;
}







