// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	article "gateway/internal/handler/article"
	comment "gateway/internal/handler/comment"
	login "gateway/internal/handler/login"
	"gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/article/create",
				Handler: article.CreateArticleHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/article/delete",
				Handler: article.DeleteArticleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/article/detail",
				Handler: article.GetArticleDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/article/favor",
				Handler: article.FavoriteArticleHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/article/like",
				Handler: article.LikeArticleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/article/list",
				Handler: article.ListArticlesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/article/search",
				Handler: article.SearchArticlesHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/article/update",
				Handler: article.UpdateArticleHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/comment/art_replies_list",
				Handler: comment.GetCommentRepliesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/comment/article_list",
				Handler: comment.GetArticleCommentsHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/comment/create",
					Handler: comment.CreateCommentHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/comment/delete",
					Handler: comment.DeleteCommentHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/comment/reply/create",
					Handler: comment.CreateReplyHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/comment/user/list",
					Handler: comment.GetUserCommentsHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/captcha",
				Handler: login.CaptchaHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/emaillogin",
				Handler: login.EmailLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: login.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/reset_password_by_email",
				Handler: login.Reset_password_by_emailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sendemail",
				Handler: login.SendEmailHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/logout",
					Handler: login.LogoutHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
