// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	login "gateway/internal/handler/login"
	"gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/captcha",
				Handler: login.CaptchaHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/emaillogin",
				Handler: login.EmailLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/refresh",
				Handler: login.RefreshTokenHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: login.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/reset_password_by_email",
				Handler: login.Reset_password_by_emailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sendemail",
				Handler: login.SendEmailHandler(serverCtx),
			},
		},
	)
}
