// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.1
// source: desc/core.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Test 接口的请求和响应消息
type TestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestRequest) Reset() {
	*x = TestRequest{}
	mi := &file_desc_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRequest) ProtoMessage() {}

func (x *TestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_desc_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRequest.ProtoReflect.Descriptor instead.
func (*TestRequest) Descriptor() ([]byte, []int) {
	return file_desc_core_proto_rawDescGZIP(), []int{0}
}

func (x *TestRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type TestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestResponse) Reset() {
	*x = TestResponse{}
	mi := &file_desc_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResponse) ProtoMessage() {}

func (x *TestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_desc_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResponse.ProtoReflect.Descriptor instead.
func (*TestResponse) Descriptor() ([]byte, []int) {
	return file_desc_core_proto_rawDescGZIP(), []int{1}
}

func (x *TestResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

type EmailLoginReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 属性的类型 属性名 = 标识符
	Email         string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Captcha       string `protobuf:"bytes,2,opt,name=captcha,proto3" json:"captcha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailLoginReq) Reset() {
	*x = EmailLoginReq{}
	mi := &file_desc_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailLoginReq) ProtoMessage() {}

func (x *EmailLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_desc_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailLoginReq.ProtoReflect.Descriptor instead.
func (*EmailLoginReq) Descriptor() ([]byte, []int) {
	return file_desc_core_proto_rawDescGZIP(), []int{2}
}

func (x *EmailLoginReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *EmailLoginReq) GetCaptcha() string {
	if x != nil {
		return x.Captcha
	}
	return ""
}

type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Uuid          string                 `protobuf:"bytes,5,opt,name=uuid,proto3" json:"uuid,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,6,opt,name=RefreshToken,proto3" json:"RefreshToken,omitempty"`
	AccessToken   string                 `protobuf:"bytes,7,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	Avatar        string                 `protobuf:"bytes,8,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Role          string                 `protobuf:"bytes,9,opt,name=role,proto3" json:"role,omitempty"`
	Sex           string                 `protobuf:"bytes,10,opt,name=sex,proto3" json:"sex,omitempty"`
	Age           uint64                 `protobuf:"varint,11,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_desc_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_desc_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_desc_core_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResp) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LoginResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoginResp) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *LoginResp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginResp) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *LoginResp) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResp) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResp) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *LoginResp) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *LoginResp) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *LoginResp) GetAge() uint64 {
	if x != nil {
		return x.Age
	}
	return 0
}

type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_desc_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_desc_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_desc_core_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RegisterResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResp) Reset() {
	*x = RegisterResp{}
	mi := &file_desc_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResp) ProtoMessage() {}

func (x *RegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_desc_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResp.ProtoReflect.Descriptor instead.
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return file_desc_core_proto_rawDescGZIP(), []int{5}
}

type ResetPasswordEmailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // 已由 gateway 做 bcrypt，core 仅落库
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordEmailReq) Reset() {
	*x = ResetPasswordEmailReq{}
	mi := &file_desc_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordEmailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordEmailReq) ProtoMessage() {}

func (x *ResetPasswordEmailReq) ProtoReflect() protoreflect.Message {
	mi := &file_desc_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordEmailReq.ProtoReflect.Descriptor instead.
func (*ResetPasswordEmailReq) Descriptor() ([]byte, []int) {
	return file_desc_core_proto_rawDescGZIP(), []int{6}
}

func (x *ResetPasswordEmailReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ResetPasswordEmailReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ResetPasswordEmailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordEmailResp) Reset() {
	*x = ResetPasswordEmailResp{}
	mi := &file_desc_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordEmailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordEmailResp) ProtoMessage() {}

func (x *ResetPasswordEmailResp) ProtoReflect() protoreflect.Message {
	mi := &file_desc_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordEmailResp.ProtoReflect.Descriptor instead.
func (*ResetPasswordEmailResp) Descriptor() ([]byte, []int) {
	return file_desc_core_proto_rawDescGZIP(), []int{7}
}

type LogoutReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=RefreshToken,proto3" json:"RefreshToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutReq) Reset() {
	*x = LogoutReq{}
	mi := &file_desc_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReq) ProtoMessage() {}

func (x *LogoutReq) ProtoReflect() protoreflect.Message {
	mi := &file_desc_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReq.ProtoReflect.Descriptor instead.
func (*LogoutReq) Descriptor() ([]byte, []int) {
	return file_desc_core_proto_rawDescGZIP(), []int{8}
}

func (x *LogoutReq) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LogoutReq) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LogoutResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResp) Reset() {
	*x = LogoutResp{}
	mi := &file_desc_core_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResp) ProtoMessage() {}

func (x *LogoutResp) ProtoReflect() protoreflect.Message {
	mi := &file_desc_core_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResp.ProtoReflect.Descriptor instead.
func (*LogoutResp) Descriptor() ([]byte, []int) {
	return file_desc_core_proto_rawDescGZIP(), []int{9}
}

// ======================================================================================================================
// 文章部分
// 文章信息结构
type ArticleInfo struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId       uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CategoryId   uint64                 `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Title        string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Summary      string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	Content      string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Cover        string                 `protobuf:"bytes,7,opt,name=cover,proto3" json:"cover,omitempty"`
	ViewCount    uint32                 `protobuf:"varint,8,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	LikeCount    uint32                 `protobuf:"varint,9,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	FavorCount   uint32                 `protobuf:"varint,10,opt,name=favor_count,json=favorCount,proto3" json:"favor_count,omitempty"`
	CommentCount uint32                 `protobuf:"varint,11,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	CreatedAt    string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // 创建时间
	UpdatedAt    string                 `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // 更新时间
	// 作者信息（可根据需要扩展）
	AuthorName    string `protobuf:"bytes,14,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`
	AuthorAvatar  string `protobuf:"bytes,15,opt,name=author_avatar,json=authorAvatar,proto3" json:"author_avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleInfo) Reset() {
	*x = ArticleInfo{}
	mi := &file_desc_core_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleInfo) ProtoMessage() {}

func (x *ArticleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_desc_core_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleInfo.ProtoReflect.Descriptor instead.
func (*ArticleInfo) Descriptor() ([]byte, []int) {
	return file_desc_core_proto_rawDescGZIP(), []int{10}
}

func (x *ArticleInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ArticleInfo) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ArticleInfo) GetCategoryId() uint64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ArticleInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ArticleInfo) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ArticleInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ArticleInfo) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *ArticleInfo) GetViewCount() uint32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *ArticleInfo) GetLikeCount() uint32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *ArticleInfo) GetFavorCount() uint32 {
	if x != nil {
		return x.FavorCount
	}
	return 0
}

func (x *ArticleInfo) GetCommentCount() uint32 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *ArticleInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ArticleInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *ArticleInfo) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *ArticleInfo) GetAuthorAvatar() string {
	if x != nil {
		return x.AuthorAvatar
	}
	return ""
}

// 创建文章
type CreateArticleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    uint64                 `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Cover         string                 `protobuf:"bytes,5,opt,name=cover,proto3" json:"cover,omitempty"`
	UserId        uint64                 `protobuf:"varint,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleReq) Reset() {
	*x = CreateArticleReq{}
	mi := &file_desc_core_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleReq) ProtoMessage() {}

func (x *CreateArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_desc_core_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleReq.ProtoReflect.Descriptor instead.
func (*CreateArticleReq) Descriptor() ([]byte, []int) {
	return file_desc_core_proto_rawDescGZIP(), []int{11}
}

func (x *CreateArticleReq) GetCategoryId() uint64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreateArticleReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateArticleReq) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *CreateArticleReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateArticleReq) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *CreateArticleReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreateArticleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleResp) Reset() {
	*x = CreateArticleResp{}
	mi := &file_desc_core_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleResp) ProtoMessage() {}

func (x *CreateArticleResp) ProtoReflect() protoreflect.Message {
	mi := &file_desc_core_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleResp.ProtoReflect.Descriptor instead.
func (*CreateArticleResp) Descriptor() ([]byte, []int) {
	return file_desc_core_proto_rawDescGZIP(), []int{12}
}

// 更新文章
type UpdateArticleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                   // 文章ID
	CategoryId    uint64                 `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"` // 分类ID（可选更新）
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`                              // 标题（可选更新）
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`                          // 摘要（可选更新）
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`                          // 内容（可选更新）
	Cover         string                 `protobuf:"bytes,6,opt,name=cover,proto3" json:"cover,omitempty"`                              // 封面（可选更新）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleReq) Reset() {
	*x = UpdateArticleReq{}
	mi := &file_desc_core_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleReq) ProtoMessage() {}

func (x *UpdateArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_desc_core_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleReq.ProtoReflect.Descriptor instead.
func (*UpdateArticleReq) Descriptor() ([]byte, []int) {
	return file_desc_core_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateArticleReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateArticleReq) GetCategoryId() uint64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *UpdateArticleReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateArticleReq) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *UpdateArticleReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateArticleReq) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

type UpdateArticleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleResp) Reset() {
	*x = UpdateArticleResp{}
	mi := &file_desc_core_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleResp) ProtoMessage() {}

func (x *UpdateArticleResp) ProtoReflect() protoreflect.Message {
	mi := &file_desc_core_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleResp.ProtoReflect.Descriptor instead.
func (*UpdateArticleResp) Descriptor() ([]byte, []int) {
	return file_desc_core_proto_rawDescGZIP(), []int{14}
}

// 删除文章（软删除）
type DeleteArticleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleReq) Reset() {
	*x = DeleteArticleReq{}
	mi := &file_desc_core_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleReq) ProtoMessage() {}

func (x *DeleteArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_desc_core_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleReq.ProtoReflect.Descriptor instead.
func (*DeleteArticleReq) Descriptor() ([]byte, []int) {
	return file_desc_core_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteArticleReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteArticleReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteArticleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleResp) Reset() {
	*x = DeleteArticleResp{}
	mi := &file_desc_core_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleResp) ProtoMessage() {}

func (x *DeleteArticleResp) ProtoReflect() protoreflect.Message {
	mi := &file_desc_core_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleResp.ProtoReflect.Descriptor instead.
func (*DeleteArticleResp) Descriptor() ([]byte, []int) {
	return file_desc_core_proto_rawDescGZIP(), []int{16}
}

// 获取文章详情
type GetArticleDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleDetailReq) Reset() {
	*x = GetArticleDetailReq{}
	mi := &file_desc_core_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleDetailReq) ProtoMessage() {}

func (x *GetArticleDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_desc_core_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleDetailReq.ProtoReflect.Descriptor instead.
func (*GetArticleDetailReq) Descriptor() ([]byte, []int) {
	return file_desc_core_proto_rawDescGZIP(), []int{17}
}

func (x *GetArticleDetailReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetArticleDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *ArticleInfo           `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleDetailResp) Reset() {
	*x = GetArticleDetailResp{}
	mi := &file_desc_core_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleDetailResp) ProtoMessage() {}

func (x *GetArticleDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_desc_core_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleDetailResp.ProtoReflect.Descriptor instead.
func (*GetArticleDetailResp) Descriptor() ([]byte, []int) {
	return file_desc_core_proto_rawDescGZIP(), []int{18}
}

func (x *GetArticleDetailResp) GetArticle() *ArticleInfo {
	if x != nil {
		return x.Article
	}
	return nil
}

// 文章列表（支持分页和筛选）
type ListArticlesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                               // 页码，从1开始
	PageSize      uint32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`       // 每页数量
	CategoryId    uint64                 `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"` // 按分类筛选（0表示不筛选）
	UserId        uint64                 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`             // 按作者筛选（0表示不筛选）
	SortBy        string                 `protobuf:"bytes,5,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`              // 排序字段：created_at, view_count, like_count
	SortOrder     string                 `protobuf:"bytes,6,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`     // 排序方式：asc, desc
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticlesReq) Reset() {
	*x = ListArticlesReq{}
	mi := &file_desc_core_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticlesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticlesReq) ProtoMessage() {}

func (x *ListArticlesReq) ProtoReflect() protoreflect.Message {
	mi := &file_desc_core_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticlesReq.ProtoReflect.Descriptor instead.
func (*ListArticlesReq) Descriptor() ([]byte, []int) {
	return file_desc_core_proto_rawDescGZIP(), []int{19}
}

func (x *ListArticlesReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListArticlesReq) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListArticlesReq) GetCategoryId() uint64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ListArticlesReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListArticlesReq) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListArticlesReq) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

type ListArticlesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Articles      []*ArticleInfo         `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`                       // 总数量
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`                         // 当前页码
	PageSize      uint32                 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticlesResp) Reset() {
	*x = ListArticlesResp{}
	mi := &file_desc_core_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticlesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticlesResp) ProtoMessage() {}

func (x *ListArticlesResp) ProtoReflect() protoreflect.Message {
	mi := &file_desc_core_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticlesResp.ProtoReflect.Descriptor instead.
func (*ListArticlesResp) Descriptor() ([]byte, []int) {
	return file_desc_core_proto_rawDescGZIP(), []int{20}
}

func (x *ListArticlesResp) GetArticles() []*ArticleInfo {
	if x != nil {
		return x.Articles
	}
	return nil
}

func (x *ListArticlesResp) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListArticlesResp) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListArticlesResp) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 搜索文章
type SearchArticlesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`                          // 搜索关键词（标题和内容）
	Page          uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`                               // 页码
	PageSize      uint32                 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`       // 每页数量
	CategoryId    uint64                 `protobuf:"varint,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"` // 按分类筛选（0表示不筛选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchArticlesReq) Reset() {
	*x = SearchArticlesReq{}
	mi := &file_desc_core_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchArticlesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchArticlesReq) ProtoMessage() {}

func (x *SearchArticlesReq) ProtoReflect() protoreflect.Message {
	mi := &file_desc_core_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchArticlesReq.ProtoReflect.Descriptor instead.
func (*SearchArticlesReq) Descriptor() ([]byte, []int) {
	return file_desc_core_proto_rawDescGZIP(), []int{21}
}

func (x *SearchArticlesReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchArticlesReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchArticlesReq) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchArticlesReq) GetCategoryId() uint64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

type SearchArticlesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Articles      []*ArticleInfo         `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchArticlesResp) Reset() {
	*x = SearchArticlesResp{}
	mi := &file_desc_core_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchArticlesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchArticlesResp) ProtoMessage() {}

func (x *SearchArticlesResp) ProtoReflect() protoreflect.Message {
	mi := &file_desc_core_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchArticlesResp.ProtoReflect.Descriptor instead.
func (*SearchArticlesResp) Descriptor() ([]byte, []int) {
	return file_desc_core_proto_rawDescGZIP(), []int{22}
}

func (x *SearchArticlesResp) GetArticles() []*ArticleInfo {
	if x != nil {
		return x.Articles
	}
	return nil
}

func (x *SearchArticlesResp) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchArticlesResp) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchArticlesResp) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 点赞文章
type LikeArticleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     uint64                 `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	IsLike        bool                   `protobuf:"varint,2,opt,name=is_like,json=isLike,proto3" json:"is_like,omitempty"` // true: 点赞, false: 取消点赞
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeArticleReq) Reset() {
	*x = LikeArticleReq{}
	mi := &file_desc_core_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeArticleReq) ProtoMessage() {}

func (x *LikeArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_desc_core_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeArticleReq.ProtoReflect.Descriptor instead.
func (*LikeArticleReq) Descriptor() ([]byte, []int) {
	return file_desc_core_proto_rawDescGZIP(), []int{23}
}

func (x *LikeArticleReq) GetArticleId() uint64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *LikeArticleReq) GetIsLike() bool {
	if x != nil {
		return x.IsLike
	}
	return false
}

type LikeArticleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LikeCount     uint32                 `protobuf:"varint,1,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"` // 返回最新点赞数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeArticleResp) Reset() {
	*x = LikeArticleResp{}
	mi := &file_desc_core_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeArticleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeArticleResp) ProtoMessage() {}

func (x *LikeArticleResp) ProtoReflect() protoreflect.Message {
	mi := &file_desc_core_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeArticleResp.ProtoReflect.Descriptor instead.
func (*LikeArticleResp) Descriptor() ([]byte, []int) {
	return file_desc_core_proto_rawDescGZIP(), []int{24}
}

func (x *LikeArticleResp) GetLikeCount() uint32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

// 收藏文章
type FavoriteArticleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     uint64                 `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	IsFavorite    bool                   `protobuf:"varint,2,opt,name=is_favorite,json=isFavorite,proto3" json:"is_favorite,omitempty"` // true: 收藏, false: 取消收藏
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteArticleReq) Reset() {
	*x = FavoriteArticleReq{}
	mi := &file_desc_core_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteArticleReq) ProtoMessage() {}

func (x *FavoriteArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_desc_core_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteArticleReq.ProtoReflect.Descriptor instead.
func (*FavoriteArticleReq) Descriptor() ([]byte, []int) {
	return file_desc_core_proto_rawDescGZIP(), []int{25}
}

func (x *FavoriteArticleReq) GetArticleId() uint64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *FavoriteArticleReq) GetIsFavorite() bool {
	if x != nil {
		return x.IsFavorite
	}
	return false
}

type FavoriteArticleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FavorCount    uint32                 `protobuf:"varint,1,opt,name=favor_count,json=favorCount,proto3" json:"favor_count,omitempty"` // 返回最新收藏数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteArticleResp) Reset() {
	*x = FavoriteArticleResp{}
	mi := &file_desc_core_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteArticleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteArticleResp) ProtoMessage() {}

func (x *FavoriteArticleResp) ProtoReflect() protoreflect.Message {
	mi := &file_desc_core_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteArticleResp.ProtoReflect.Descriptor instead.
func (*FavoriteArticleResp) Descriptor() ([]byte, []int) {
	return file_desc_core_proto_rawDescGZIP(), []int{26}
}

func (x *FavoriteArticleResp) GetFavorCount() uint32 {
	if x != nil {
		return x.FavorCount
	}
	return 0
}

var File_desc_core_proto protoreflect.FileDescriptor

const file_desc_core_proto_rawDesc = "" +
	"\n" +
	"\x0fdesc/core.proto\x12\x04core\"\x1f\n" +
	"\vTestRequest\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"$\n" +
	"\fTestResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply\"?\n" +
	"\rEmailLoginReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x18\n" +
	"\acaptcha\x18\x02 \x01(\tR\acaptcha\"\x85\x02\n" +
	"\tLoginResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x12\n" +
	"\x04uuid\x18\x05 \x01(\tR\x04uuid\x12\"\n" +
	"\fRefreshToken\x18\x06 \x01(\tR\fRefreshToken\x12 \n" +
	"\vAccessToken\x18\a \x01(\tR\vAccessToken\x12\x16\n" +
	"\x06avatar\x18\b \x01(\tR\x06avatar\x12\x12\n" +
	"\x04role\x18\t \x01(\tR\x04role\x12\x10\n" +
	"\x03sex\x18\n" +
	" \x01(\tR\x03sex\x12\x10\n" +
	"\x03age\x18\v \x01(\x04R\x03age\"S\n" +
	"\vRegisterReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\x0e\n" +
	"\fRegisterResp\"I\n" +
	"\x15ResetPasswordEmailReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x18\n" +
	"\x16ResetPasswordEmailResp\"Q\n" +
	"\tLogoutReq\x12 \n" +
	"\vAccessToken\x18\x01 \x01(\tR\vAccessToken\x12\"\n" +
	"\fRefreshToken\x18\x02 \x01(\tR\fRefreshToken\"\f\n" +
	"\n" +
	"LogoutResp\"\xbf\x03\n" +
	"\vArticleInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\x04R\n" +
	"categoryId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x14\n" +
	"\x05cover\x18\a \x01(\tR\x05cover\x12\x1d\n" +
	"\n" +
	"view_count\x18\b \x01(\rR\tviewCount\x12\x1d\n" +
	"\n" +
	"like_count\x18\t \x01(\rR\tlikeCount\x12\x1f\n" +
	"\vfavor_count\x18\n" +
	" \x01(\rR\n" +
	"favorCount\x12#\n" +
	"\rcomment_count\x18\v \x01(\rR\fcommentCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\tR\tupdatedAt\x12\x1f\n" +
	"\vauthor_name\x18\x0e \x01(\tR\n" +
	"authorName\x12#\n" +
	"\rauthor_avatar\x18\x0f \x01(\tR\fauthorAvatar\"\xac\x01\n" +
	"\x10CreateArticleReq\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x04R\n" +
	"categoryId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x14\n" +
	"\x05cover\x18\x05 \x01(\tR\x05cover\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\x04R\x06userId\"\x13\n" +
	"\x11CreateArticleResp\"\xa3\x01\n" +
	"\x10UpdateArticleReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x04R\n" +
	"categoryId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x14\n" +
	"\x05cover\x18\x06 \x01(\tR\x05cover\"\x13\n" +
	"\x11UpdateArticleResp\";\n" +
	"\x10DeleteArticleReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\"\x13\n" +
	"\x11DeleteArticleResp\"%\n" +
	"\x13GetArticleDetailReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"C\n" +
	"\x14GetArticleDetailResp\x12+\n" +
	"\aarticle\x18\x01 \x01(\v2\x11.core.ArticleInfoR\aarticle\"\xb4\x01\n" +
	"\x0fListArticlesReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\x04R\n" +
	"categoryId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x04R\x06userId\x12\x17\n" +
	"\asort_by\x18\x05 \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x06 \x01(\tR\tsortOrder\"\x88\x01\n" +
	"\x10ListArticlesResp\x12-\n" +
	"\barticles\x18\x01 \x03(\v2\x11.core.ArticleInfoR\barticles\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\rR\bpageSize\"\x7f\n" +
	"\x11SearchArticlesReq\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\rR\bpageSize\x12\x1f\n" +
	"\vcategory_id\x18\x04 \x01(\x04R\n" +
	"categoryId\"\x8a\x01\n" +
	"\x12SearchArticlesResp\x12-\n" +
	"\barticles\x18\x01 \x03(\v2\x11.core.ArticleInfoR\barticles\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\rR\bpageSize\"H\n" +
	"\x0eLikeArticleReq\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\x04R\tarticleId\x12\x17\n" +
	"\ais_like\x18\x02 \x01(\bR\x06isLike\"0\n" +
	"\x0fLikeArticleResp\x12\x1d\n" +
	"\n" +
	"like_count\x18\x01 \x01(\rR\tlikeCount\"T\n" +
	"\x12FavoriteArticleReq\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\x04R\tarticleId\x12\x1f\n" +
	"\vis_favorite\x18\x02 \x01(\bR\n" +
	"isFavorite\"6\n" +
	"\x13FavoriteArticleResp\x12\x1f\n" +
	"\vfavor_count\x18\x01 \x01(\rR\n" +
	"favorCount2\xca\x06\n" +
	"\x04Core\x12-\n" +
	"\x04Test\x12\x11.core.TestRequest\x1a\x12.core.TestResponse\x123\n" +
	"\bRegister\x12\x11.core.RegisterReq\x1a\x12.core.RegisterResp\"\x00\x124\n" +
	"\n" +
	"EmailLogin\x12\x13.core.EmailLoginReq\x1a\x0f.core.LoginResp\"\x00\x12S\n" +
	"\x14ResetPasswordByEmail\x12\x1b.core.ResetPasswordEmailReq\x1a\x1c.core.ResetPasswordEmailResp\"\x00\x12-\n" +
	"\x06Logout\x12\x0f.core.LogoutReq\x1a\x10.core.LogoutResp\"\x00\x12B\n" +
	"\rCreateArticle\x12\x16.core.CreateArticleReq\x1a\x17.core.CreateArticleResp\"\x00\x12B\n" +
	"\rUpdateArticle\x12\x16.core.UpdateArticleReq\x1a\x17.core.UpdateArticleResp\"\x00\x12B\n" +
	"\rDeleteArticle\x12\x16.core.DeleteArticleReq\x1a\x17.core.DeleteArticleResp\"\x00\x12K\n" +
	"\x10GetArticleDetail\x12\x19.core.GetArticleDetailReq\x1a\x1a.core.GetArticleDetailResp\"\x00\x12?\n" +
	"\fListArticles\x12\x15.core.ListArticlesReq\x1a\x16.core.ListArticlesResp\"\x00\x12E\n" +
	"\x0eSearchArticles\x12\x17.core.SearchArticlesReq\x1a\x18.core.SearchArticlesResp\"\x00\x12<\n" +
	"\vLikeArticle\x12\x14.core.LikeArticleReq\x1a\x15.core.LikeArticleResp\"\x00\x12E\n" +
	"\fFavorArticle\x12\x18.core.FavoriteArticleReq\x1a\x19.core.FavoriteArticleResp\"\x00B\bZ\x06./coreb\x06proto3"

var (
	file_desc_core_proto_rawDescOnce sync.Once
	file_desc_core_proto_rawDescData []byte
)

func file_desc_core_proto_rawDescGZIP() []byte {
	file_desc_core_proto_rawDescOnce.Do(func() {
		file_desc_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_desc_core_proto_rawDesc), len(file_desc_core_proto_rawDesc)))
	})
	return file_desc_core_proto_rawDescData
}

var file_desc_core_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_desc_core_proto_goTypes = []any{
	(*TestRequest)(nil),            // 0: core.TestRequest
	(*TestResponse)(nil),           // 1: core.TestResponse
	(*EmailLoginReq)(nil),          // 2: core.EmailLoginReq
	(*LoginResp)(nil),              // 3: core.LoginResp
	(*RegisterReq)(nil),            // 4: core.RegisterReq
	(*RegisterResp)(nil),           // 5: core.RegisterResp
	(*ResetPasswordEmailReq)(nil),  // 6: core.ResetPasswordEmailReq
	(*ResetPasswordEmailResp)(nil), // 7: core.ResetPasswordEmailResp
	(*LogoutReq)(nil),              // 8: core.LogoutReq
	(*LogoutResp)(nil),             // 9: core.LogoutResp
	(*ArticleInfo)(nil),            // 10: core.ArticleInfo
	(*CreateArticleReq)(nil),       // 11: core.CreateArticleReq
	(*CreateArticleResp)(nil),      // 12: core.CreateArticleResp
	(*UpdateArticleReq)(nil),       // 13: core.UpdateArticleReq
	(*UpdateArticleResp)(nil),      // 14: core.UpdateArticleResp
	(*DeleteArticleReq)(nil),       // 15: core.DeleteArticleReq
	(*DeleteArticleResp)(nil),      // 16: core.DeleteArticleResp
	(*GetArticleDetailReq)(nil),    // 17: core.GetArticleDetailReq
	(*GetArticleDetailResp)(nil),   // 18: core.GetArticleDetailResp
	(*ListArticlesReq)(nil),        // 19: core.ListArticlesReq
	(*ListArticlesResp)(nil),       // 20: core.ListArticlesResp
	(*SearchArticlesReq)(nil),      // 21: core.SearchArticlesReq
	(*SearchArticlesResp)(nil),     // 22: core.SearchArticlesResp
	(*LikeArticleReq)(nil),         // 23: core.LikeArticleReq
	(*LikeArticleResp)(nil),        // 24: core.LikeArticleResp
	(*FavoriteArticleReq)(nil),     // 25: core.FavoriteArticleReq
	(*FavoriteArticleResp)(nil),    // 26: core.FavoriteArticleResp
}
var file_desc_core_proto_depIdxs = []int32{
	10, // 0: core.GetArticleDetailResp.article:type_name -> core.ArticleInfo
	10, // 1: core.ListArticlesResp.articles:type_name -> core.ArticleInfo
	10, // 2: core.SearchArticlesResp.articles:type_name -> core.ArticleInfo
	0,  // 3: core.Core.Test:input_type -> core.TestRequest
	4,  // 4: core.Core.Register:input_type -> core.RegisterReq
	2,  // 5: core.Core.EmailLogin:input_type -> core.EmailLoginReq
	6,  // 6: core.Core.ResetPasswordByEmail:input_type -> core.ResetPasswordEmailReq
	8,  // 7: core.Core.Logout:input_type -> core.LogoutReq
	11, // 8: core.Core.CreateArticle:input_type -> core.CreateArticleReq
	13, // 9: core.Core.UpdateArticle:input_type -> core.UpdateArticleReq
	15, // 10: core.Core.DeleteArticle:input_type -> core.DeleteArticleReq
	17, // 11: core.Core.GetArticleDetail:input_type -> core.GetArticleDetailReq
	19, // 12: core.Core.ListArticles:input_type -> core.ListArticlesReq
	21, // 13: core.Core.SearchArticles:input_type -> core.SearchArticlesReq
	23, // 14: core.Core.LikeArticle:input_type -> core.LikeArticleReq
	25, // 15: core.Core.FavorArticle:input_type -> core.FavoriteArticleReq
	1,  // 16: core.Core.Test:output_type -> core.TestResponse
	5,  // 17: core.Core.Register:output_type -> core.RegisterResp
	3,  // 18: core.Core.EmailLogin:output_type -> core.LoginResp
	7,  // 19: core.Core.ResetPasswordByEmail:output_type -> core.ResetPasswordEmailResp
	9,  // 20: core.Core.Logout:output_type -> core.LogoutResp
	12, // 21: core.Core.CreateArticle:output_type -> core.CreateArticleResp
	14, // 22: core.Core.UpdateArticle:output_type -> core.UpdateArticleResp
	16, // 23: core.Core.DeleteArticle:output_type -> core.DeleteArticleResp
	18, // 24: core.Core.GetArticleDetail:output_type -> core.GetArticleDetailResp
	20, // 25: core.Core.ListArticles:output_type -> core.ListArticlesResp
	22, // 26: core.Core.SearchArticles:output_type -> core.SearchArticlesResp
	24, // 27: core.Core.LikeArticle:output_type -> core.LikeArticleResp
	26, // 28: core.Core.FavorArticle:output_type -> core.FavoriteArticleResp
	16, // [16:29] is the sub-list for method output_type
	3,  // [3:16] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_desc_core_proto_init() }
func file_desc_core_proto_init() {
	if File_desc_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_desc_core_proto_rawDesc), len(file_desc_core_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_desc_core_proto_goTypes,
		DependencyIndexes: file_desc_core_proto_depIdxs,
		MessageInfos:      file_desc_core_proto_msgTypes,
	}.Build()
	File_desc_core_proto = out.File
	file_desc_core_proto_goTypes = nil
	file_desc_core_proto_depIdxs = nil
}
