// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.4
// source: desc/core.proto

package core

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Core_Test_FullMethodName                 = "/core.Core/Test"
	Core_Register_FullMethodName             = "/core.Core/Register"
	Core_EmailLogin_FullMethodName           = "/core.Core/EmailLogin"
	Core_ResetPasswordByEmail_FullMethodName = "/core.Core/ResetPasswordByEmail"
	Core_Logout_FullMethodName               = "/core.Core/Logout"
	Core_CreateCategory_FullMethodName       = "/core.Core/CreateCategory"
	Core_ListCategories_FullMethodName       = "/core.Core/ListCategories"
	Core_DeleteCategory_FullMethodName       = "/core.Core/DeleteCategory"
	Core_CreateArticle_FullMethodName        = "/core.Core/CreateArticle"
	Core_UpdateArticle_FullMethodName        = "/core.Core/UpdateArticle"
	Core_DeleteArticle_FullMethodName        = "/core.Core/DeleteArticle"
	Core_GetArticleDetail_FullMethodName     = "/core.Core/GetArticleDetail"
	Core_ListArticles_FullMethodName         = "/core.Core/ListArticles"
	Core_SearchArticles_FullMethodName       = "/core.Core/SearchArticles"
	Core_LikeArticle_FullMethodName          = "/core.Core/LikeArticle"
	Core_FavorArticle_FullMethodName         = "/core.Core/FavorArticle"
	Core_LikeComment_FullMethodName          = "/core.Core/LikeComment"
	Core_CreateComment_FullMethodName        = "/core.Core/CreateComment"
	Core_CreateReply_FullMethodName          = "/core.Core/CreateReply"
	Core_DeleteComment_FullMethodName        = "/core.Core/DeleteComment"
	Core_GetArticleComments_FullMethodName   = "/core.Core/GetArticleComments"
	Core_GetCommentReplies_FullMethodName    = "/core.Core/GetCommentReplies"
	Core_GetUserComments_FullMethodName      = "/core.Core/GetUserComments"
)

// CoreClient is the client API for Core service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 所有 RPC 方法统一定义在这里
type CoreClient interface {
	// 测试接口
	Test(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error)
	// Login 部分
	Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
	EmailLogin(ctx context.Context, in *EmailLoginReq, opts ...grpc.CallOption) (*LoginResp, error)
	ResetPasswordByEmail(ctx context.Context, in *ResetPasswordEmailReq, opts ...grpc.CallOption) (*ResetPasswordEmailResp, error)
	Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*LogoutResp, error)
	// Category 部分
	CreateCategory(ctx context.Context, in *CreateCategoryReq, opts ...grpc.CallOption) (*CreateCategoryResp, error)
	ListCategories(ctx context.Context, in *ListCategoriesReq, opts ...grpc.CallOption) (*ListCategoriesResp, error)
	DeleteCategory(ctx context.Context, in *DeleteCategoryReq, opts ...grpc.CallOption) (*DeleteCategoryResp, error)
	// Article 部分
	CreateArticle(ctx context.Context, in *CreateArticleReq, opts ...grpc.CallOption) (*CreateArticleResp, error)
	UpdateArticle(ctx context.Context, in *UpdateArticleReq, opts ...grpc.CallOption) (*UpdateArticleResp, error)
	DeleteArticle(ctx context.Context, in *DeleteArticleReq, opts ...grpc.CallOption) (*DeleteArticleResp, error)
	GetArticleDetail(ctx context.Context, in *GetArticleDetailReq, opts ...grpc.CallOption) (*GetArticleDetailResp, error)
	ListArticles(ctx context.Context, in *ListArticlesReq, opts ...grpc.CallOption) (*ListArticlesResp, error)
	SearchArticles(ctx context.Context, in *SearchArticlesReq, opts ...grpc.CallOption) (*SearchArticlesResp, error)
	// interaction 部分
	LikeArticle(ctx context.Context, in *LikeArticleReq, opts ...grpc.CallOption) (*LikeArticleResp, error)
	FavorArticle(ctx context.Context, in *FavoriteArticleReq, opts ...grpc.CallOption) (*FavoriteArticleResp, error)
	LikeComment(ctx context.Context, in *LikeCommentReq, opts ...grpc.CallOption) (*LikeCommentResp, error)
	// comment 部分
	CreateComment(ctx context.Context, in *CreateCommentReq, opts ...grpc.CallOption) (*CreateCommentResp, error)
	CreateReply(ctx context.Context, in *CreateReplyReq, opts ...grpc.CallOption) (*CreateReplyResp, error)
	DeleteComment(ctx context.Context, in *DeleteCommentReq, opts ...grpc.CallOption) (*DeleteCommentResp, error)
	GetArticleComments(ctx context.Context, in *GetArticleCommentsReq, opts ...grpc.CallOption) (*GetArticleCommentsResp, error)
	GetCommentReplies(ctx context.Context, in *GetCommentRepliesReq, opts ...grpc.CallOption) (*GetCommentRepliesResp, error)
	GetUserComments(ctx context.Context, in *GetUserCommentsReq, opts ...grpc.CallOption) (*GetUserCommentsResp, error)
}

type coreClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreClient(cc grpc.ClientConnInterface) CoreClient {
	return &coreClient{cc}
}

func (c *coreClient) Test(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestResponse)
	err := c.cc.Invoke(ctx, Core_Test_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResp)
	err := c.cc.Invoke(ctx, Core_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) EmailLogin(ctx context.Context, in *EmailLoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResp)
	err := c.cc.Invoke(ctx, Core_EmailLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) ResetPasswordByEmail(ctx context.Context, in *ResetPasswordEmailReq, opts ...grpc.CallOption) (*ResetPasswordEmailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetPasswordEmailResp)
	err := c.cc.Invoke(ctx, Core_ResetPasswordByEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*LogoutResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogoutResp)
	err := c.cc.Invoke(ctx, Core_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) CreateCategory(ctx context.Context, in *CreateCategoryReq, opts ...grpc.CallOption) (*CreateCategoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCategoryResp)
	err := c.cc.Invoke(ctx, Core_CreateCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) ListCategories(ctx context.Context, in *ListCategoriesReq, opts ...grpc.CallOption) (*ListCategoriesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCategoriesResp)
	err := c.cc.Invoke(ctx, Core_ListCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) DeleteCategory(ctx context.Context, in *DeleteCategoryReq, opts ...grpc.CallOption) (*DeleteCategoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCategoryResp)
	err := c.cc.Invoke(ctx, Core_DeleteCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) CreateArticle(ctx context.Context, in *CreateArticleReq, opts ...grpc.CallOption) (*CreateArticleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateArticleResp)
	err := c.cc.Invoke(ctx, Core_CreateArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) UpdateArticle(ctx context.Context, in *UpdateArticleReq, opts ...grpc.CallOption) (*UpdateArticleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateArticleResp)
	err := c.cc.Invoke(ctx, Core_UpdateArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) DeleteArticle(ctx context.Context, in *DeleteArticleReq, opts ...grpc.CallOption) (*DeleteArticleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteArticleResp)
	err := c.cc.Invoke(ctx, Core_DeleteArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) GetArticleDetail(ctx context.Context, in *GetArticleDetailReq, opts ...grpc.CallOption) (*GetArticleDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArticleDetailResp)
	err := c.cc.Invoke(ctx, Core_GetArticleDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) ListArticles(ctx context.Context, in *ListArticlesReq, opts ...grpc.CallOption) (*ListArticlesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListArticlesResp)
	err := c.cc.Invoke(ctx, Core_ListArticles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) SearchArticles(ctx context.Context, in *SearchArticlesReq, opts ...grpc.CallOption) (*SearchArticlesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchArticlesResp)
	err := c.cc.Invoke(ctx, Core_SearchArticles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) LikeArticle(ctx context.Context, in *LikeArticleReq, opts ...grpc.CallOption) (*LikeArticleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LikeArticleResp)
	err := c.cc.Invoke(ctx, Core_LikeArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) FavorArticle(ctx context.Context, in *FavoriteArticleReq, opts ...grpc.CallOption) (*FavoriteArticleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FavoriteArticleResp)
	err := c.cc.Invoke(ctx, Core_FavorArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) LikeComment(ctx context.Context, in *LikeCommentReq, opts ...grpc.CallOption) (*LikeCommentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LikeCommentResp)
	err := c.cc.Invoke(ctx, Core_LikeComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) CreateComment(ctx context.Context, in *CreateCommentReq, opts ...grpc.CallOption) (*CreateCommentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCommentResp)
	err := c.cc.Invoke(ctx, Core_CreateComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) CreateReply(ctx context.Context, in *CreateReplyReq, opts ...grpc.CallOption) (*CreateReplyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateReplyResp)
	err := c.cc.Invoke(ctx, Core_CreateReply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) DeleteComment(ctx context.Context, in *DeleteCommentReq, opts ...grpc.CallOption) (*DeleteCommentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCommentResp)
	err := c.cc.Invoke(ctx, Core_DeleteComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) GetArticleComments(ctx context.Context, in *GetArticleCommentsReq, opts ...grpc.CallOption) (*GetArticleCommentsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArticleCommentsResp)
	err := c.cc.Invoke(ctx, Core_GetArticleComments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) GetCommentReplies(ctx context.Context, in *GetCommentRepliesReq, opts ...grpc.CallOption) (*GetCommentRepliesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCommentRepliesResp)
	err := c.cc.Invoke(ctx, Core_GetCommentReplies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) GetUserComments(ctx context.Context, in *GetUserCommentsReq, opts ...grpc.CallOption) (*GetUserCommentsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserCommentsResp)
	err := c.cc.Invoke(ctx, Core_GetUserComments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreServer is the server API for Core service.
// All implementations must embed UnimplementedCoreServer
// for forward compatibility.
//
// 所有 RPC 方法统一定义在这里
type CoreServer interface {
	// 测试接口
	Test(context.Context, *TestRequest) (*TestResponse, error)
	// Login 部分
	Register(context.Context, *RegisterReq) (*RegisterResp, error)
	EmailLogin(context.Context, *EmailLoginReq) (*LoginResp, error)
	ResetPasswordByEmail(context.Context, *ResetPasswordEmailReq) (*ResetPasswordEmailResp, error)
	Logout(context.Context, *LogoutReq) (*LogoutResp, error)
	// Category 部分
	CreateCategory(context.Context, *CreateCategoryReq) (*CreateCategoryResp, error)
	ListCategories(context.Context, *ListCategoriesReq) (*ListCategoriesResp, error)
	DeleteCategory(context.Context, *DeleteCategoryReq) (*DeleteCategoryResp, error)
	// Article 部分
	CreateArticle(context.Context, *CreateArticleReq) (*CreateArticleResp, error)
	UpdateArticle(context.Context, *UpdateArticleReq) (*UpdateArticleResp, error)
	DeleteArticle(context.Context, *DeleteArticleReq) (*DeleteArticleResp, error)
	GetArticleDetail(context.Context, *GetArticleDetailReq) (*GetArticleDetailResp, error)
	ListArticles(context.Context, *ListArticlesReq) (*ListArticlesResp, error)
	SearchArticles(context.Context, *SearchArticlesReq) (*SearchArticlesResp, error)
	// interaction 部分
	LikeArticle(context.Context, *LikeArticleReq) (*LikeArticleResp, error)
	FavorArticle(context.Context, *FavoriteArticleReq) (*FavoriteArticleResp, error)
	LikeComment(context.Context, *LikeCommentReq) (*LikeCommentResp, error)
	// comment 部分
	CreateComment(context.Context, *CreateCommentReq) (*CreateCommentResp, error)
	CreateReply(context.Context, *CreateReplyReq) (*CreateReplyResp, error)
	DeleteComment(context.Context, *DeleteCommentReq) (*DeleteCommentResp, error)
	GetArticleComments(context.Context, *GetArticleCommentsReq) (*GetArticleCommentsResp, error)
	GetCommentReplies(context.Context, *GetCommentRepliesReq) (*GetCommentRepliesResp, error)
	GetUserComments(context.Context, *GetUserCommentsReq) (*GetUserCommentsResp, error)
	mustEmbedUnimplementedCoreServer()
}

// UnimplementedCoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoreServer struct{}

func (UnimplementedCoreServer) Test(context.Context, *TestRequest) (*TestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Test not implemented")
}
func (UnimplementedCoreServer) Register(context.Context, *RegisterReq) (*RegisterResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedCoreServer) EmailLogin(context.Context, *EmailLoginReq) (*LoginResp, error) {
	return nil, status.Error(codes.Unimplemented, "method EmailLogin not implemented")
}
func (UnimplementedCoreServer) ResetPasswordByEmail(context.Context, *ResetPasswordEmailReq) (*ResetPasswordEmailResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetPasswordByEmail not implemented")
}
func (UnimplementedCoreServer) Logout(context.Context, *LogoutReq) (*LogoutResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedCoreServer) CreateCategory(context.Context, *CreateCategoryReq) (*CreateCategoryResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCategory not implemented")
}
func (UnimplementedCoreServer) ListCategories(context.Context, *ListCategoriesReq) (*ListCategoriesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCategories not implemented")
}
func (UnimplementedCoreServer) DeleteCategory(context.Context, *DeleteCategoryReq) (*DeleteCategoryResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCategory not implemented")
}
func (UnimplementedCoreServer) CreateArticle(context.Context, *CreateArticleReq) (*CreateArticleResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateArticle not implemented")
}
func (UnimplementedCoreServer) UpdateArticle(context.Context, *UpdateArticleReq) (*UpdateArticleResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateArticle not implemented")
}
func (UnimplementedCoreServer) DeleteArticle(context.Context, *DeleteArticleReq) (*DeleteArticleResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteArticle not implemented")
}
func (UnimplementedCoreServer) GetArticleDetail(context.Context, *GetArticleDetailReq) (*GetArticleDetailResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArticleDetail not implemented")
}
func (UnimplementedCoreServer) ListArticles(context.Context, *ListArticlesReq) (*ListArticlesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListArticles not implemented")
}
func (UnimplementedCoreServer) SearchArticles(context.Context, *SearchArticlesReq) (*SearchArticlesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchArticles not implemented")
}
func (UnimplementedCoreServer) LikeArticle(context.Context, *LikeArticleReq) (*LikeArticleResp, error) {
	return nil, status.Error(codes.Unimplemented, "method LikeArticle not implemented")
}
func (UnimplementedCoreServer) FavorArticle(context.Context, *FavoriteArticleReq) (*FavoriteArticleResp, error) {
	return nil, status.Error(codes.Unimplemented, "method FavorArticle not implemented")
}
func (UnimplementedCoreServer) LikeComment(context.Context, *LikeCommentReq) (*LikeCommentResp, error) {
	return nil, status.Error(codes.Unimplemented, "method LikeComment not implemented")
}
func (UnimplementedCoreServer) CreateComment(context.Context, *CreateCommentReq) (*CreateCommentResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateComment not implemented")
}
func (UnimplementedCoreServer) CreateReply(context.Context, *CreateReplyReq) (*CreateReplyResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateReply not implemented")
}
func (UnimplementedCoreServer) DeleteComment(context.Context, *DeleteCommentReq) (*DeleteCommentResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteComment not implemented")
}
func (UnimplementedCoreServer) GetArticleComments(context.Context, *GetArticleCommentsReq) (*GetArticleCommentsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArticleComments not implemented")
}
func (UnimplementedCoreServer) GetCommentReplies(context.Context, *GetCommentRepliesReq) (*GetCommentRepliesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCommentReplies not implemented")
}
func (UnimplementedCoreServer) GetUserComments(context.Context, *GetUserCommentsReq) (*GetUserCommentsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserComments not implemented")
}
func (UnimplementedCoreServer) mustEmbedUnimplementedCoreServer() {}
func (UnimplementedCoreServer) testEmbeddedByValue()              {}

// UnsafeCoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreServer will
// result in compilation errors.
type UnsafeCoreServer interface {
	mustEmbedUnimplementedCoreServer()
}

func RegisterCoreServer(s grpc.ServiceRegistrar, srv CoreServer) {
	// If the following call panics, it indicates UnimplementedCoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Core_ServiceDesc, srv)
}

func _Core_Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).Test(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_Test_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).Test(ctx, req.(*TestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).Register(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_EmailLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailLoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).EmailLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_EmailLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).EmailLogin(ctx, req.(*EmailLoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_ResetPasswordByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetPasswordEmailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).ResetPasswordByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_ResetPasswordByEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).ResetPasswordByEmail(ctx, req.(*ResetPasswordEmailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).Logout(ctx, req.(*LogoutReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_CreateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCategoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).CreateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_CreateCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).CreateCategory(ctx, req.(*CreateCategoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_ListCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCategoriesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).ListCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_ListCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).ListCategories(ctx, req.(*ListCategoriesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_DeleteCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCategoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).DeleteCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_DeleteCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).DeleteCategory(ctx, req.(*DeleteCategoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_CreateArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateArticleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).CreateArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_CreateArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).CreateArticle(ctx, req.(*CreateArticleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_UpdateArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateArticleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).UpdateArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_UpdateArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).UpdateArticle(ctx, req.(*UpdateArticleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_DeleteArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteArticleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).DeleteArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_DeleteArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).DeleteArticle(ctx, req.(*DeleteArticleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_GetArticleDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArticleDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).GetArticleDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_GetArticleDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).GetArticleDetail(ctx, req.(*GetArticleDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_ListArticles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListArticlesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).ListArticles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_ListArticles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).ListArticles(ctx, req.(*ListArticlesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_SearchArticles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchArticlesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).SearchArticles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_SearchArticles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).SearchArticles(ctx, req.(*SearchArticlesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_LikeArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeArticleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).LikeArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_LikeArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).LikeArticle(ctx, req.(*LikeArticleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_FavorArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FavoriteArticleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).FavorArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_FavorArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).FavorArticle(ctx, req.(*FavoriteArticleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_LikeComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeCommentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).LikeComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_LikeComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).LikeComment(ctx, req.(*LikeCommentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_CreateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).CreateComment(ctx, req.(*CreateCommentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_CreateReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReplyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).CreateReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_CreateReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).CreateReply(ctx, req.(*CreateReplyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCommentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_DeleteComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).DeleteComment(ctx, req.(*DeleteCommentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_GetArticleComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArticleCommentsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).GetArticleComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_GetArticleComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).GetArticleComments(ctx, req.(*GetArticleCommentsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_GetCommentReplies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommentRepliesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).GetCommentReplies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_GetCommentReplies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).GetCommentReplies(ctx, req.(*GetCommentRepliesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_GetUserComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserCommentsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).GetUserComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_GetUserComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).GetUserComments(ctx, req.(*GetUserCommentsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Core_ServiceDesc is the grpc.ServiceDesc for Core service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Core_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core.Core",
	HandlerType: (*CoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Test",
			Handler:    _Core_Test_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _Core_Register_Handler,
		},
		{
			MethodName: "EmailLogin",
			Handler:    _Core_EmailLogin_Handler,
		},
		{
			MethodName: "ResetPasswordByEmail",
			Handler:    _Core_ResetPasswordByEmail_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _Core_Logout_Handler,
		},
		{
			MethodName: "CreateCategory",
			Handler:    _Core_CreateCategory_Handler,
		},
		{
			MethodName: "ListCategories",
			Handler:    _Core_ListCategories_Handler,
		},
		{
			MethodName: "DeleteCategory",
			Handler:    _Core_DeleteCategory_Handler,
		},
		{
			MethodName: "CreateArticle",
			Handler:    _Core_CreateArticle_Handler,
		},
		{
			MethodName: "UpdateArticle",
			Handler:    _Core_UpdateArticle_Handler,
		},
		{
			MethodName: "DeleteArticle",
			Handler:    _Core_DeleteArticle_Handler,
		},
		{
			MethodName: "GetArticleDetail",
			Handler:    _Core_GetArticleDetail_Handler,
		},
		{
			MethodName: "ListArticles",
			Handler:    _Core_ListArticles_Handler,
		},
		{
			MethodName: "SearchArticles",
			Handler:    _Core_SearchArticles_Handler,
		},
		{
			MethodName: "LikeArticle",
			Handler:    _Core_LikeArticle_Handler,
		},
		{
			MethodName: "FavorArticle",
			Handler:    _Core_FavorArticle_Handler,
		},
		{
			MethodName: "LikeComment",
			Handler:    _Core_LikeComment_Handler,
		},
		{
			MethodName: "CreateComment",
			Handler:    _Core_CreateComment_Handler,
		},
		{
			MethodName: "CreateReply",
			Handler:    _Core_CreateReply_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _Core_DeleteComment_Handler,
		},
		{
			MethodName: "GetArticleComments",
			Handler:    _Core_GetArticleComments_Handler,
		},
		{
			MethodName: "GetCommentReplies",
			Handler:    _Core_GetCommentReplies_Handler,
		},
		{
			MethodName: "GetUserComments",
			Handler:    _Core_GetUserComments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "desc/core.proto",
}
