// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.1
// source: desc/core.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestRequest) Reset() {
	*x = TestRequest{}
	mi := &file_desc_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRequest) ProtoMessage() {}

func (x *TestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_desc_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRequest.ProtoReflect.Descriptor instead.
func (*TestRequest) Descriptor() ([]byte, []int) {
	return file_desc_core_proto_rawDescGZIP(), []int{0}
}

func (x *TestRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type TestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestResponse) Reset() {
	*x = TestResponse{}
	mi := &file_desc_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResponse) ProtoMessage() {}

func (x *TestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_desc_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResponse.ProtoReflect.Descriptor instead.
func (*TestResponse) Descriptor() ([]byte, []int) {
	return file_desc_core_proto_rawDescGZIP(), []int{1}
}

func (x *TestResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

type LoginReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 属性的类型 属性名 = 标识符
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_desc_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_desc_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_desc_core_proto_rawDescGZIP(), []int{2}
}

func (x *LoginReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type EmailLoginReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 属性的类型 属性名 = 标识符
	Email         string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Captcha       string `protobuf:"bytes,2,opt,name=captcha,proto3" json:"captcha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailLoginReq) Reset() {
	*x = EmailLoginReq{}
	mi := &file_desc_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailLoginReq) ProtoMessage() {}

func (x *EmailLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_desc_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailLoginReq.ProtoReflect.Descriptor instead.
func (*EmailLoginReq) Descriptor() ([]byte, []int) {
	return file_desc_core_proto_rawDescGZIP(), []int{3}
}

func (x *EmailLoginReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *EmailLoginReq) GetCaptcha() string {
	if x != nil {
		return x.Captcha
	}
	return ""
}

type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Uuid          string                 `protobuf:"bytes,5,opt,name=uuid,proto3" json:"uuid,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,6,opt,name=RefreshToken,proto3" json:"RefreshToken,omitempty"`
	AccessToken   string                 `protobuf:"bytes,7,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	Avatar        string                 `protobuf:"bytes,8,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Role          string                 `protobuf:"bytes,9,opt,name=role,proto3" json:"role,omitempty"`
	Sex           string                 `protobuf:"bytes,10,opt,name=sex,proto3" json:"sex,omitempty"`
	Age           uint64                 `protobuf:"varint,11,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_desc_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_desc_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_desc_core_proto_rawDescGZIP(), []int{4}
}

func (x *LoginResp) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LoginResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoginResp) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *LoginResp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginResp) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *LoginResp) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResp) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResp) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *LoginResp) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *LoginResp) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *LoginResp) GetAge() uint64 {
	if x != nil {
		return x.Age
	}
	return 0
}

type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Captcha       string                 `protobuf:"bytes,3,opt,name=captcha,proto3" json:"captcha,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_desc_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_desc_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_desc_core_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterReq) GetCaptcha() string {
	if x != nil {
		return x.Captcha
	}
	return ""
}

func (x *RegisterReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RegisterResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResp) Reset() {
	*x = RegisterResp{}
	mi := &file_desc_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResp) ProtoMessage() {}

func (x *RegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_desc_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResp.ProtoReflect.Descriptor instead.
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return file_desc_core_proto_rawDescGZIP(), []int{6}
}

type EmailCaptchaReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailCaptchaReq) Reset() {
	*x = EmailCaptchaReq{}
	mi := &file_desc_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailCaptchaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailCaptchaReq) ProtoMessage() {}

func (x *EmailCaptchaReq) ProtoReflect() protoreflect.Message {
	mi := &file_desc_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailCaptchaReq.ProtoReflect.Descriptor instead.
func (*EmailCaptchaReq) Descriptor() ([]byte, []int) {
	return file_desc_core_proto_rawDescGZIP(), []int{7}
}

func (x *EmailCaptchaReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type EmailCaptchaResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailCaptchaResp) Reset() {
	*x = EmailCaptchaResp{}
	mi := &file_desc_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailCaptchaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailCaptchaResp) ProtoMessage() {}

func (x *EmailCaptchaResp) ProtoReflect() protoreflect.Message {
	mi := &file_desc_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailCaptchaResp.ProtoReflect.Descriptor instead.
func (*EmailCaptchaResp) Descriptor() ([]byte, []int) {
	return file_desc_core_proto_rawDescGZIP(), []int{8}
}

type ResetPasswordEmailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Captcha       string                 `protobuf:"bytes,3,opt,name=captcha,proto3" json:"captcha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordEmailReq) Reset() {
	*x = ResetPasswordEmailReq{}
	mi := &file_desc_core_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordEmailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordEmailReq) ProtoMessage() {}

func (x *ResetPasswordEmailReq) ProtoReflect() protoreflect.Message {
	mi := &file_desc_core_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordEmailReq.ProtoReflect.Descriptor instead.
func (*ResetPasswordEmailReq) Descriptor() ([]byte, []int) {
	return file_desc_core_proto_rawDescGZIP(), []int{9}
}

func (x *ResetPasswordEmailReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ResetPasswordEmailReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ResetPasswordEmailReq) GetCaptcha() string {
	if x != nil {
		return x.Captcha
	}
	return ""
}

type ResetPasswordEmailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordEmailResp) Reset() {
	*x = ResetPasswordEmailResp{}
	mi := &file_desc_core_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordEmailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordEmailResp) ProtoMessage() {}

func (x *ResetPasswordEmailResp) ProtoReflect() protoreflect.Message {
	mi := &file_desc_core_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordEmailResp.ProtoReflect.Descriptor instead.
func (*ResetPasswordEmailResp) Descriptor() ([]byte, []int) {
	return file_desc_core_proto_rawDescGZIP(), []int{10}
}

type LogoutReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=RefreshToken,proto3" json:"RefreshToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutReq) Reset() {
	*x = LogoutReq{}
	mi := &file_desc_core_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReq) ProtoMessage() {}

func (x *LogoutReq) ProtoReflect() protoreflect.Message {
	mi := &file_desc_core_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReq.ProtoReflect.Descriptor instead.
func (*LogoutReq) Descriptor() ([]byte, []int) {
	return file_desc_core_proto_rawDescGZIP(), []int{11}
}

func (x *LogoutReq) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LogoutReq) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LogoutResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResp) Reset() {
	*x = LogoutResp{}
	mi := &file_desc_core_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResp) ProtoMessage() {}

func (x *LogoutResp) ProtoReflect() protoreflect.Message {
	mi := &file_desc_core_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResp.ProtoReflect.Descriptor instead.
func (*LogoutResp) Descriptor() ([]byte, []int) {
	return file_desc_core_proto_rawDescGZIP(), []int{12}
}

var File_desc_core_proto protoreflect.FileDescriptor

const file_desc_core_proto_rawDesc = "" +
	"\n" +
	"\x0fdesc/core.proto\x12\x04core\"\x1f\n" +
	"\vTestRequest\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"$\n" +
	"\fTestResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply\":\n" +
	"\bLoginReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"?\n" +
	"\rEmailLoginReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x18\n" +
	"\acaptcha\x18\x02 \x01(\tR\acaptcha\"\x85\x02\n" +
	"\tLoginResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x12\n" +
	"\x04uuid\x18\x05 \x01(\tR\x04uuid\x12\"\n" +
	"\fRefreshToken\x18\x06 \x01(\tR\fRefreshToken\x12 \n" +
	"\vAccessToken\x18\a \x01(\tR\vAccessToken\x12\x16\n" +
	"\x06avatar\x18\b \x01(\tR\x06avatar\x12\x12\n" +
	"\x04role\x18\t \x01(\tR\x04role\x12\x10\n" +
	"\x03sex\x18\n" +
	" \x01(\tR\x03sex\x12\x10\n" +
	"\x03age\x18\v \x01(\x04R\x03age\"m\n" +
	"\vRegisterReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x18\n" +
	"\acaptcha\x18\x03 \x01(\tR\acaptcha\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"\x0e\n" +
	"\fRegisterResp\"'\n" +
	"\x0fEmailCaptchaReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"\x12\n" +
	"\x10EmailCaptchaResp\"c\n" +
	"\x15ResetPasswordEmailReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x18\n" +
	"\acaptcha\x18\x03 \x01(\tR\acaptcha\"\x18\n" +
	"\x16ResetPasswordEmailResp\"Q\n" +
	"\tLogoutReq\x12 \n" +
	"\vAccessToken\x18\x01 \x01(\tR\vAccessToken\x12\"\n" +
	"\fRefreshToken\x18\x02 \x01(\tR\fRefreshToken\"\f\n" +
	"\n" +
	"LogoutResp2\x91\x03\n" +
	"\x04Core\x12-\n" +
	"\x04Test\x12\x11.core.TestRequest\x1a\x12.core.TestResponse\x123\n" +
	"\bRegister\x12\x11.core.RegisterReq\x1a\x12.core.RegisterResp\"\x00\x12*\n" +
	"\x05Login\x12\x0e.core.LoginReq\x1a\x0f.core.LoginResp\"\x00\x124\n" +
	"\n" +
	"EmailLogin\x12\x13.core.EmailLoginReq\x1a\x0f.core.LoginResp\"\x00\x12S\n" +
	"\x14ResetPasswordByEmail\x12\x1b.core.ResetPasswordEmailReq\x1a\x1c.core.ResetPasswordEmailResp\"\x00\x12-\n" +
	"\x06Logout\x12\x0f.core.LogoutReq\x1a\x10.core.LogoutResp\"\x00\x12?\n" +
	"\fEmailCaptcha\x12\x15.core.EmailCaptchaReq\x1a\x16.core.EmailCaptchaResp\"\x00B\x06Z\x04./pbb\x06proto3"

var (
	file_desc_core_proto_rawDescOnce sync.Once
	file_desc_core_proto_rawDescData []byte
)

func file_desc_core_proto_rawDescGZIP() []byte {
	file_desc_core_proto_rawDescOnce.Do(func() {
		file_desc_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_desc_core_proto_rawDesc), len(file_desc_core_proto_rawDesc)))
	})
	return file_desc_core_proto_rawDescData
}

var file_desc_core_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_desc_core_proto_goTypes = []any{
	(*TestRequest)(nil),            // 0: core.TestRequest
	(*TestResponse)(nil),           // 1: core.TestResponse
	(*LoginReq)(nil),               // 2: core.LoginReq
	(*EmailLoginReq)(nil),          // 3: core.EmailLoginReq
	(*LoginResp)(nil),              // 4: core.LoginResp
	(*RegisterReq)(nil),            // 5: core.RegisterReq
	(*RegisterResp)(nil),           // 6: core.RegisterResp
	(*EmailCaptchaReq)(nil),        // 7: core.EmailCaptchaReq
	(*EmailCaptchaResp)(nil),       // 8: core.EmailCaptchaResp
	(*ResetPasswordEmailReq)(nil),  // 9: core.ResetPasswordEmailReq
	(*ResetPasswordEmailResp)(nil), // 10: core.ResetPasswordEmailResp
	(*LogoutReq)(nil),              // 11: core.LogoutReq
	(*LogoutResp)(nil),             // 12: core.LogoutResp
}
var file_desc_core_proto_depIdxs = []int32{
	0,  // 0: core.Core.Test:input_type -> core.TestRequest
	5,  // 1: core.Core.Register:input_type -> core.RegisterReq
	2,  // 2: core.Core.Login:input_type -> core.LoginReq
	3,  // 3: core.Core.EmailLogin:input_type -> core.EmailLoginReq
	9,  // 4: core.Core.ResetPasswordByEmail:input_type -> core.ResetPasswordEmailReq
	11, // 5: core.Core.Logout:input_type -> core.LogoutReq
	7,  // 6: core.Core.EmailCaptcha:input_type -> core.EmailCaptchaReq
	1,  // 7: core.Core.Test:output_type -> core.TestResponse
	6,  // 8: core.Core.Register:output_type -> core.RegisterResp
	4,  // 9: core.Core.Login:output_type -> core.LoginResp
	4,  // 10: core.Core.EmailLogin:output_type -> core.LoginResp
	10, // 11: core.Core.ResetPasswordByEmail:output_type -> core.ResetPasswordEmailResp
	12, // 12: core.Core.Logout:output_type -> core.LogoutResp
	8,  // 13: core.Core.EmailCaptcha:output_type -> core.EmailCaptchaResp
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_desc_core_proto_init() }
func file_desc_core_proto_init() {
	if File_desc_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_desc_core_proto_rawDesc), len(file_desc_core_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_desc_core_proto_goTypes,
		DependencyIndexes: file_desc_core_proto_depIdxs,
		MessageInfos:      file_desc_core_proto_msgTypes,
	}.Build()
	File_desc_core_proto = out.File
	file_desc_core_proto_goTypes = nil
	file_desc_core_proto_depIdxs = nil
}
