// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package comment

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	commentFieldNames          = builder.RawFieldNames(&Comment{})
	commentRows                = strings.Join(commentFieldNames, ",")
	commentRowsExpectAutoSet   = strings.Join(stringx.Remove(commentFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	commentRowsWithPlaceHolder = strings.Join(stringx.Remove(commentFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	commentModel interface {
		Insert(ctx context.Context, data *Comment) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Comment, error)
		Update(ctx context.Context, data *Comment) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultCommentModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Comment struct {
		Id          uint64       `db:"id"`            // 评论ID
		ArticleId   uint64       `db:"article_id"`    // 文章ID
		UserId      uint64       `db:"user_id"`       // 用户ID
		ParentId    uint64       `db:"parent_id"`     // 父评论ID（一级评论=0，二级评论=一级评论ID）
		RootId      uint64       `db:"root_id"`       // 根评论ID（一级评论=id，二级评论=一级评论ID）
		ReplyToId   uint64       `db:"reply_to_id"`   // 回复目标用户ID
		ReplyToName string       `db:"reply_to_name"` // 回复目标用户名
		Content     string       `db:"content"`       // 评论内容
		LikeCount   uint64       `db:"like_count"`    // 点赞数
		ChildCount  uint64       `db:"child_count"`   // 子评论数
		CreatedAt   time.Time    `db:"created_at"`    // 创建时间
		DeletedAt   sql.NullTime `db:"deleted_at"`    // 删除时间
	}
)

func newCommentModel(conn sqlx.SqlConn) *defaultCommentModel {
	return &defaultCommentModel{
		conn:  conn,
		table: "`comment`",
	}
}

func (m *defaultCommentModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCommentModel) FindOne(ctx context.Context, id uint64) (*Comment, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", commentRows, m.table)
	var resp Comment
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCommentModel) Insert(ctx context.Context, data *Comment) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, commentRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ArticleId, data.UserId, data.ParentId, data.RootId, data.ReplyToId, data.ReplyToName, data.Content, data.LikeCount, data.ChildCount, data.DeletedAt)
	return ret, err
}

func (m *defaultCommentModel) Update(ctx context.Context, data *Comment) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, commentRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ArticleId, data.UserId, data.ParentId, data.RootId, data.ReplyToId, data.ReplyToName, data.Content, data.LikeCount, data.ChildCount, data.DeletedAt, data.Id)
	return err
}

func (m *defaultCommentModel) tableName() string {
	return m.table
}
