// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type ArticleInfo struct {
	Id           uint64 `json:"id"`
	UserId       uint64 `json:"user_id"`
	CategoryId   uint64 `json:"category_id"`
	Title        string `json:"title"`
	Summary      string `json:"summary"`
	Content      string `json:"content"`
	Cover        string `json:"cover"`
	ViewCount    uint32 `json:"view_count"`
	LikeCount    uint32 `json:"like_count"`
	FavorCount   uint32 `json:"favor_count"`
	CommentCount uint32 `json:"comment_count"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
	AuthorName   string `json:"author_name"`
	AuthorAvatar string `json:"author_avatar"`
}

type CaptchaData struct {
	CaptchaId string `json:"captcha_id"`
	PicBase64 string `json:"pic_base64"`
}

type CaptchaResp struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data CaptchaData `json:"data"`
}

type CreateArticleReq struct {
	CategoryId uint64 `json:"category_id"`
	Title      string `json:"title"`
	Summary    string `json:"summary"`
	Content    string `json:"content"`
	Cover      string `json:"cover"`
	UserId     uint64 `json:"user_id"`
}

type CreateArticleResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type DeleteArticleReq struct {
	Id uint64 `json:"id"`
}

type DeleteArticleResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type EmailReq struct {
	Email string `json:"email"`
}

type EmailResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type FavorArticleData struct {
	FavorCount uint32 `json:"favor_count"`
}

type FavorArticleReq struct {
	ArticleId  uint64 `json:"article_id"`
	IsFavorite bool   `json:"is_favorite"`
}

type FavorArticleResp struct {
	Code int              `json:"code"`
	Msg  string           `json:"msg"`
	Data FavorArticleData `json:"data"`
}

type GetArticleDetailReq struct {
	Id uint64 `json:"id"`
}

type GetArticleDetailResp struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data ArticleInfo `json:"data"`
}

type LikeArticleData struct {
	LikeCount uint32 `json:"like_count"`
}

type LikeArticleReq struct {
	ArticleId uint64 `json:"article_id"`
	IsLike    bool   `json:"is_like"`
}

type LikeArticleResp struct {
	Code int             `json:"code"`
	Msg  string          `json:"msg"`
	Data LikeArticleData `json:"data"`
}

type ListArticlesData struct {
	Articles []ArticleInfo `json:"articles"`
	Total    uint32        `json:"total"`
	Page     uint32        `json:"page"`
	PageSize uint32        `json:"page_size"`
}

type ListArticlesReq struct {
	Page       uint32 `json:"page"`
	PageSize   uint32 `json:"page_size"`
	CategoryId uint64 `json:"category_id,optional"`
	UserId     uint64 `json:"user_id,optional"`
	SortBy     string `json:"sort_by,optional"`
	SortOrder  string `json:"sort_order,optional"`
}

type ListArticlesResp struct {
	Code int              `json:"code"`
	Msg  string           `json:"msg"`
	Data ListArticlesData `json:"data"`
}

type LoginData struct {
	Id           uint64 `json:"id"`
	Name         string `json:"name"`
	Phone        string `json:"phone"`
	Email        string `json:"email"`
	Uuid         string `json:"uuid"`
	Avatar       string `json:"avatar"`
	Role         string `json:"role"`
	Sex          string `json:"sex"`
	Age          uint64 `json:"age"`
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

type LoginEmailReq struct {
	Email   string `json:"email"`
	Captcha string `json:"captcha"`
}

type LoginResp struct {
	Code int       `json:"code"`
	Msg  string    `json:"msg"`
	Data LoginData `json:"data"`
}

type LogoutReq struct {
}

type LogoutResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type RefreshReq struct {
}

type RegisterReq struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Captcha  string `json:"captcha"`
}

type RegisterResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type ResetPasswordReq struct {
	Email           string `json:"email"`
	Captcha         string `json:"captcha"`
	NewPassword     string `json:"newpassword"`
	ConfirmPassword string `json:"confirmpassword"`
}

type ResetPasswordResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type SearchArticlesData struct {
	Articles []ArticleInfo `json:"articles"`
	Total    uint32        `json:"total"`
	Page     uint32        `json:"page"`
	PageSize uint32        `json:"page_size"`
}

type SearchArticlesReq struct {
	Keyword    string `json:"keyword"`
	Page       uint32 `json:"page"`
	PageSize   uint32 `json:"page_size"`
	CategoryId uint64 `json:"category_id,optional"`
}

type SearchArticlesResp struct {
	Code int                `json:"code"`
	Msg  string             `json:"msg"`
	Data SearchArticlesData `json:"data"`
}

type UpdateArticleReq struct {
	Id         uint64 `json:"id"`
	CategoryId uint64 `json:"category_id,optional"`
	Title      string `json:"title,optional"`
	Summary    string `json:"summary,optional"`
	Content    string `json:"content,optional"`
	Cover      string `json:"cover,optional"`
}

type UpdateArticleResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}
