// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type CaptchaData struct {
	CaptchaId string `json:"captcha_id"`
	PicBase64 string `json:"pic_base64"`
}

type CaptchaResp struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data CaptchaData `json:"data"`
}

type EmailReq struct {
	Email string `json:"email"`
}

type EmailResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type LoginData struct {
	Id           uint64 `json:"id"`
	Name         string `json:"name"`
	Phone        string `json:"phone"`
	Email        string `json:"email"`
	Uuid         string `json:"uuid"`
	Avatar       string `json:"avatar"`
	Role         string `json:"role"`
	Sex          string `json:"sex"`
	Age          uint64 `json:"age"`
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

type LoginEmailReq struct {
	Email   string `json:"email"`
	Captcha string `json:"captcha"`
}

type LoginResp struct {
	Code int       `json:"code"`
	Msg  string    `json:"msg"`
	Data LoginData `json:"data"`
}

type RefreshReq struct {
}

type RegisterReq struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Captcha  string `json:"captcha"`
}

type RegisterResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type ResetPasswordReq struct {
	Email    string `json:"email"`
	Captcha  string `json:"captcha"`
	Password string `json:"password"`
	Confirm  string `json:"confirm"`
}

type ResetPasswordResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}
