// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type CaptchaResp struct {
	CaptchaId string `json:"captcha_id"` // 验证码的唯一标识，用于提交验证时使用
	PicBase64 string `json:"pic_base64"` // base64编码的图像内容，前端可直接用于 <img>
}

type EmailReq struct {
	Email string `json:"email"`
}

type EmailResp struct {
	Success bool `json:"success"`
}

type LoginEmailReq struct {
	Email   string `json:"email"`
	Captcha string `json:"captcha"`
}

type LoginReq struct {
	Name      string `json:"name"`
	Password  string `json:"password"`
	Code      string `json:"code"`
	CaptchaId string `json:"captcha_id"`
}

type LoginResp struct {
	Id     uint64 `json:"id"`
	Name   string `json:"name"`
	Phone  string `json:"phone"`
	Email  string `json:"email"`
	Uuid   string `json:"uuid"`
	Avatar string `json:"avatar"`
	Role   string `json:"role"`
	Sex    string `json:"sex"`
	Age    uint64 `json:"age"`
}

type RefreshReq struct {
}

type RegisterReq struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Captcha  string `json:"captcha"`
}

type RegisterResp struct {
	Code uint64 `json:"code"`
	Msg  string `json:"msg"`
}

type ResetPasswordReq struct {
	Email    string `json:"email"`
	Captcha  string `json:"captcha"`
	Password string `json:"password"`
	Confirm  string `json:"confirm"`
}

type ResetPasswordResp struct {
	Success bool `json:"success"`
}
