// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package interaction

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	interactionCommentFieldNames          = builder.RawFieldNames(&InteractionComment{})
	interactionCommentRows                = strings.Join(interactionCommentFieldNames, ",")
	interactionCommentRowsExpectAutoSet   = strings.Join(stringx.Remove(interactionCommentFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	interactionCommentRowsWithPlaceHolder = strings.Join(stringx.Remove(interactionCommentFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	interactionCommentModel interface {
		Insert(ctx context.Context, data *InteractionComment) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*InteractionComment, error)
		Update(ctx context.Context, data *InteractionComment) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultInteractionCommentModel struct {
		conn  sqlx.SqlConn
		table string
	}

	InteractionComment struct {
		Id        uint64       `db:"id"`         // 主键ID
		CreatedAt time.Time    `db:"created_at"` // 创建时间
		UpdatedAt time.Time    `db:"updated_at"` // 更新时间
		DeletedAt sql.NullTime `db:"deleted_at"` // 软删除时间
		UserId    uint64       `db:"user_id"`    // 用户ID
		ArticleId uint64       `db:"article_id"` // 文章ID
		Content   string       `db:"content"`    // 评论内容
	}
)

func newInteractionCommentModel(conn sqlx.SqlConn) *defaultInteractionCommentModel {
	return &defaultInteractionCommentModel{
		conn:  conn,
		table: "`interaction_comment`",
	}
}

func (m *defaultInteractionCommentModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultInteractionCommentModel) FindOne(ctx context.Context, id uint64) (*InteractionComment, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", interactionCommentRows, m.table)
	var resp InteractionComment
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultInteractionCommentModel) Insert(ctx context.Context, data *InteractionComment) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, interactionCommentRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.DeletedAt, data.UserId, data.ArticleId, data.Content)
	return ret, err
}

func (m *defaultInteractionCommentModel) Update(ctx context.Context, data *InteractionComment) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, interactionCommentRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.DeletedAt, data.UserId, data.ArticleId, data.Content, data.Id)
	return err
}

func (m *defaultInteractionCommentModel) tableName() string {
	return m.table
}
