// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: desc/agent.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestRequest) Reset() {
	*x = TestRequest{}
	mi := &file_desc_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRequest) ProtoMessage() {}

func (x *TestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_desc_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRequest.ProtoReflect.Descriptor instead.
func (*TestRequest) Descriptor() ([]byte, []int) {
	return file_desc_agent_proto_rawDescGZIP(), []int{0}
}

func (x *TestRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type TestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestResponse) Reset() {
	*x = TestResponse{}
	mi := &file_desc_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResponse) ProtoMessage() {}

func (x *TestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_desc_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResponse.ProtoReflect.Descriptor instead.
func (*TestResponse) Descriptor() ([]byte, []int) {
	return file_desc_agent_proto_rawDescGZIP(), []int{1}
}

func (x *TestResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_desc_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_desc_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_desc_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ChatRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        string                 `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_desc_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_desc_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_desc_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ChatResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

type ChatStreamChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Done          bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	MessageId     string                 `protobuf:"bytes,4,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatStreamChunk) Reset() {
	*x = ChatStreamChunk{}
	mi := &file_desc_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatStreamChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatStreamChunk) ProtoMessage() {}

func (x *ChatStreamChunk) ProtoReflect() protoreflect.Message {
	mi := &file_desc_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatStreamChunk.ProtoReflect.Descriptor instead.
func (*ChatStreamChunk) Descriptor() ([]byte, []int) {
	return file_desc_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ChatStreamChunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatStreamChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *ChatStreamChunk) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatStreamChunk) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type SwitchRetrieverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchRetrieverRequest) Reset() {
	*x = SwitchRetrieverRequest{}
	mi := &file_desc_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchRetrieverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchRetrieverRequest) ProtoMessage() {}

func (x *SwitchRetrieverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_desc_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchRetrieverRequest.ProtoReflect.Descriptor instead.
func (*SwitchRetrieverRequest) Descriptor() ([]byte, []int) {
	return file_desc_agent_proto_rawDescGZIP(), []int{5}
}

func (x *SwitchRetrieverRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

type SwitchRetrieverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchRetrieverResponse) Reset() {
	*x = SwitchRetrieverResponse{}
	mi := &file_desc_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchRetrieverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchRetrieverResponse) ProtoMessage() {}

func (x *SwitchRetrieverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_desc_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchRetrieverResponse.ProtoReflect.Descriptor instead.
func (*SwitchRetrieverResponse) Descriptor() ([]byte, []int) {
	return file_desc_agent_proto_rawDescGZIP(), []int{6}
}

func (x *SwitchRetrieverResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildRequest) Reset() {
	*x = BuildRequest{}
	mi := &file_desc_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildRequest) ProtoMessage() {}

func (x *BuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_desc_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildRequest.ProtoReflect.Descriptor instead.
func (*BuildRequest) Descriptor() ([]byte, []int) {
	return file_desc_agent_proto_rawDescGZIP(), []int{7}
}

func (x *BuildRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

type BuildResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	DocCount      int32                  `protobuf:"varint,2,opt,name=doc_count,json=docCount,proto3" json:"doc_count,omitempty"`
	ChunkCount    int32                  `protobuf:"varint,3,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildResponse) Reset() {
	*x = BuildResponse{}
	mi := &file_desc_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildResponse) ProtoMessage() {}

func (x *BuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_desc_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildResponse.ProtoReflect.Descriptor instead.
func (*BuildResponse) Descriptor() ([]byte, []int) {
	return file_desc_agent_proto_rawDescGZIP(), []int{8}
}

func (x *BuildResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BuildResponse) GetDocCount() int32 {
	if x != nil {
		return x.DocCount
	}
	return 0
}

func (x *BuildResponse) GetChunkCount() int32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

type ListCollectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsRequest) Reset() {
	*x = ListCollectionsRequest{}
	mi := &file_desc_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsRequest) ProtoMessage() {}

func (x *ListCollectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_desc_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsRequest.ProtoReflect.Descriptor instead.
func (*ListCollectionsRequest) Descriptor() ([]byte, []int) {
	return file_desc_agent_proto_rawDescGZIP(), []int{9}
}

type CollectionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DocCount      int32                  `protobuf:"varint,2,opt,name=doc_count,json=docCount,proto3" json:"doc_count,omitempty"`
	ChunkCount    int32                  `protobuf:"varint,3,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionInfo) Reset() {
	*x = CollectionInfo{}
	mi := &file_desc_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionInfo) ProtoMessage() {}

func (x *CollectionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_desc_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionInfo.ProtoReflect.Descriptor instead.
func (*CollectionInfo) Descriptor() ([]byte, []int) {
	return file_desc_agent_proto_rawDescGZIP(), []int{10}
}

func (x *CollectionInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CollectionInfo) GetDocCount() int32 {
	if x != nil {
		return x.DocCount
	}
	return 0
}

func (x *CollectionInfo) GetChunkCount() int32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

func (x *CollectionInfo) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ListCollectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collections   []*CollectionInfo      `protobuf:"bytes,1,rep,name=collections,proto3" json:"collections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsResponse) Reset() {
	*x = ListCollectionsResponse{}
	mi := &file_desc_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsResponse) ProtoMessage() {}

func (x *ListCollectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_desc_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsResponse.ProtoReflect.Descriptor instead.
func (*ListCollectionsResponse) Descriptor() ([]byte, []int) {
	return file_desc_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ListCollectionsResponse) GetCollections() []*CollectionInfo {
	if x != nil {
		return x.Collections
	}
	return nil
}

type DeleteCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCollectionRequest) Reset() {
	*x = DeleteCollectionRequest{}
	mi := &file_desc_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCollectionRequest) ProtoMessage() {}

func (x *DeleteCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_desc_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCollectionRequest.ProtoReflect.Descriptor instead.
func (*DeleteCollectionRequest) Descriptor() ([]byte, []int) {
	return file_desc_agent_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteCollectionRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

type DeleteCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCollectionResponse) Reset() {
	*x = DeleteCollectionResponse{}
	mi := &file_desc_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCollectionResponse) ProtoMessage() {}

func (x *DeleteCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_desc_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCollectionResponse.ProtoReflect.Descriptor instead.
func (*DeleteCollectionResponse) Descriptor() ([]byte, []int) {
	return file_desc_agent_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteCollectionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_desc_agent_proto protoreflect.FileDescriptor

const file_desc_agent_proto_rawDesc = "" +
	"\n" +
	"\x10desc/agent.proto\x12\x05agent\"\x1f\n" +
	"\vTestRequest\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"$\n" +
	"\fTestResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply\")\n" +
	"\vChatRequest\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\"&\n" +
	"\fChatResponse\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer\"}\n" +
	"\x0fChatStreamChunk\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x04 \x01(\tR\tmessageId\"8\n" +
	"\x16SwitchRetrieverRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\"3\n" +
	"\x17SwitchRetrieverResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\".\n" +
	"\fBuildRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\"g\n" +
	"\rBuildResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1b\n" +
	"\tdoc_count\x18\x02 \x01(\x05R\bdocCount\x12\x1f\n" +
	"\vchunk_count\x18\x03 \x01(\x05R\n" +
	"chunkCount\"\x18\n" +
	"\x16ListCollectionsRequest\"x\n" +
	"\x0eCollectionInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tdoc_count\x18\x02 \x01(\x05R\bdocCount\x12\x1f\n" +
	"\vchunk_count\x18\x03 \x01(\x05R\n" +
	"chunkCount\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\"R\n" +
	"\x17ListCollectionsResponse\x127\n" +
	"\vcollections\x18\x01 \x03(\v2\x15.agent.CollectionInfoR\vcollections\"9\n" +
	"\x17DeleteCollectionRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\"4\n" +
	"\x18DeleteCollectionResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xd2\x03\n" +
	"\x05Agent\x12/\n" +
	"\x04Test\x12\x12.agent.TestRequest\x1a\x13.agent.TestResponse\x12/\n" +
	"\x04Chat\x12\x12.agent.ChatRequest\x1a\x13.agent.ChatResponse\x12:\n" +
	"\n" +
	"ChatStream\x12\x12.agent.ChatRequest\x1a\x16.agent.ChatStreamChunk0\x01\x12P\n" +
	"\x0fSwitchRetriever\x12\x1d.agent.SwitchRetrieverRequest\x1a\x1e.agent.SwitchRetrieverResponse\x122\n" +
	"\x05Build\x12\x13.agent.BuildRequest\x1a\x14.agent.BuildResponse\x12P\n" +
	"\x0fListCollections\x12\x1d.agent.ListCollectionsRequest\x1a\x1e.agent.ListCollectionsResponse\x12S\n" +
	"\x10DeleteCollection\x12\x1e.agent.DeleteCollectionRequest\x1a\x1f.agent.DeleteCollectionResponseB\tZ\a./agentb\x06proto3"

var (
	file_desc_agent_proto_rawDescOnce sync.Once
	file_desc_agent_proto_rawDescData []byte
)

func file_desc_agent_proto_rawDescGZIP() []byte {
	file_desc_agent_proto_rawDescOnce.Do(func() {
		file_desc_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_desc_agent_proto_rawDesc), len(file_desc_agent_proto_rawDesc)))
	})
	return file_desc_agent_proto_rawDescData
}

var file_desc_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_desc_agent_proto_goTypes = []any{
	(*TestRequest)(nil),              // 0: agent.TestRequest
	(*TestResponse)(nil),             // 1: agent.TestResponse
	(*ChatRequest)(nil),              // 2: agent.ChatRequest
	(*ChatResponse)(nil),             // 3: agent.ChatResponse
	(*ChatStreamChunk)(nil),          // 4: agent.ChatStreamChunk
	(*SwitchRetrieverRequest)(nil),   // 5: agent.SwitchRetrieverRequest
	(*SwitchRetrieverResponse)(nil),  // 6: agent.SwitchRetrieverResponse
	(*BuildRequest)(nil),             // 7: agent.BuildRequest
	(*BuildResponse)(nil),            // 8: agent.BuildResponse
	(*ListCollectionsRequest)(nil),   // 9: agent.ListCollectionsRequest
	(*CollectionInfo)(nil),           // 10: agent.CollectionInfo
	(*ListCollectionsResponse)(nil),  // 11: agent.ListCollectionsResponse
	(*DeleteCollectionRequest)(nil),  // 12: agent.DeleteCollectionRequest
	(*DeleteCollectionResponse)(nil), // 13: agent.DeleteCollectionResponse
}
var file_desc_agent_proto_depIdxs = []int32{
	10, // 0: agent.ListCollectionsResponse.collections:type_name -> agent.CollectionInfo
	0,  // 1: agent.Agent.Test:input_type -> agent.TestRequest
	2,  // 2: agent.Agent.Chat:input_type -> agent.ChatRequest
	2,  // 3: agent.Agent.ChatStream:input_type -> agent.ChatRequest
	5,  // 4: agent.Agent.SwitchRetriever:input_type -> agent.SwitchRetrieverRequest
	7,  // 5: agent.Agent.Build:input_type -> agent.BuildRequest
	9,  // 6: agent.Agent.ListCollections:input_type -> agent.ListCollectionsRequest
	12, // 7: agent.Agent.DeleteCollection:input_type -> agent.DeleteCollectionRequest
	1,  // 8: agent.Agent.Test:output_type -> agent.TestResponse
	3,  // 9: agent.Agent.Chat:output_type -> agent.ChatResponse
	4,  // 10: agent.Agent.ChatStream:output_type -> agent.ChatStreamChunk
	6,  // 11: agent.Agent.SwitchRetriever:output_type -> agent.SwitchRetrieverResponse
	8,  // 12: agent.Agent.Build:output_type -> agent.BuildResponse
	11, // 13: agent.Agent.ListCollections:output_type -> agent.ListCollectionsResponse
	13, // 14: agent.Agent.DeleteCollection:output_type -> agent.DeleteCollectionResponse
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_desc_agent_proto_init() }
func file_desc_agent_proto_init() {
	if File_desc_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_desc_agent_proto_rawDesc), len(file_desc_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_desc_agent_proto_goTypes,
		DependencyIndexes: file_desc_agent_proto_depIdxs,
		MessageInfos:      file_desc_agent_proto_msgTypes,
	}.Build()
	File_desc_agent_proto = out.File
	file_desc_agent_proto_goTypes = nil
	file_desc_agent_proto_depIdxs = nil
}
